"use client";

/**
 * Deep Dive: Payment Systems Reliability
 * Section 15 of 16
 */

import Link from "next/link";
import { SystemDesignLayout } from "@/components/SystemDesignLayout";
import {
  Subsection,
  Insight,
  Pitfall,
  InterviewTip,
  BulletItem,
  DataTable,
  DeepDiveHeader,
} from "@/components/DeepDiveComponents";

export default function PaymentReliabilityPage() {
  return (
    <SystemDesignLayout
      title="Payment Reliability"
      description="Ensuring money moves exactly once"
      currentSection="deep-dives"
    >
      <Link
        href="/nebula/system-design/deep-dives"
        className="inline-flex items-center gap-2 text-muted-foreground hover:text-primary text-sm mb-5 transition-colors"
      >
        &larr; Back to Deep Dives
      </Link>

      <DeepDiveHeader
        number={15}
        title="Payment Systems Reliability"
        subtitle="Ensuring money moves exactly once"
        color="amber"
      />

      <Subsection title="Idempotency: The Safe Retry Pattern" color="amber">
        <p className="text-sm text-muted-foreground mb-4">
          <strong className="text-foreground">Idempotency</strong> is the mathematical guarantee
          that repeating an action produces the same result. In payments, it answers: &quot;The
          network timed out... did the payment go through, or should I click Pay again?&quot;
        </p>

        <h4 className="text-sm font-semibold text-foreground mb-2">The Double Charge Trap</h4>
        <DataTable
          headers={["Step", "What Happens", "Risk"]}
          rows={[
            ["1", "User clicks \"Pay $100\"", ""],
            ["2", "Server sends request to Bank", ""],
            ["3", "Bank charges $100, sends \"Success\"", ""],
            ["4", "Network dies before server can respond to user", "User sees spinner"],
            ["5", "User refreshes, clicks \"Pay $100\" again", ""],
            ["6", "Without idempotency: Bank charges another $100", "Double charge!"],
          ]}
        />

        <h4 className="text-sm font-semibold text-foreground mb-2 mt-4">The Solution: Idempotency Keys</h4>
        <p className="text-sm text-muted-foreground mb-3">
          A unique ID (UUID) generated by the <strong className="text-foreground">Client</strong>
          before the request is sent. The server tracks which keys it has processed.
        </p>

        <div className="bg-muted/30 p-4 rounded-lg mb-4 font-mono text-sm">
          <p className="text-muted-foreground mb-2">{"// Request 1:"}</p>
          <p className="text-foreground">POST /charge {"{"} amount: 100, key: &quot;Key_123&quot; {"}"}</p>
          <p className="text-foreground">→ Server checks DB: &quot;Have I seen Key_123?&quot; → NO</p>
          <p className="text-foreground">→ Process payment, save result, return &quot;Success&quot;</p>
          <p className="text-muted-foreground mt-4 mb-2">{"// Request 2 (Retry after timeout):"}</p>
          <p className="text-foreground">POST /charge {"{"} amount: 100, key: &quot;Key_123&quot; {"}"}</p>
          <p className="text-foreground">→ Server checks DB: &quot;Have I seen Key_123?&quot; → YES</p>
          <p className="text-foreground">→ Return saved result WITHOUT contacting Bank</p>
        </div>

        <h4 className="text-sm font-semibold text-foreground mb-2">Edge Cases (Principal Level)</h4>
        <DataTable
          headers={["Edge Case", "Problem", "Solution"]}
          rows={[
            [
              <strong key="race">Race Condition</strong>,
              "Two requests arrive at exact same millisecond",
              "Atomic DB lock: first request writes \"Pending\" entry",
            ],
            [
              <strong key="conflict">Parameter Conflict</strong>,
              "Same key sent with $50, then $100",
              "Return HTTP 409 Conflict (key misuse)",
            ],
            [
              <strong key="expiry">Key Expiry</strong>,
              "Store keys forever = DB bloat",
              "24-48 hour TTL. Retry loops don't last 3 days.",
            ],
          ]}
        />

        <Insight title="The Safe Retry Policy">
          The goal of idempotency is to allow clients to Retry Aggressively. A Principal TPM
          says: &quot;We should build idempotency so we can retry infinitely without fear.
          Retries maximize reliability (Gold Metric), but only if they are safe.&quot;
        </Insight>
      </Subsection>

      <Subsection title="Crypto-Shredding: The Eject Button" color="amber">
        <p className="text-sm text-muted-foreground mb-4">
          In a massive distributed system, data is everywhere: Primary DB, Read Replicas, Caches,
          Data Lakes, and Cold Backups. When a user asks to be deleted, finding and scrubbing
          their data from all these places is operationally impossible.
        </p>

        <h4 className="text-sm font-semibold text-foreground mb-2">The Solution</h4>
        <p className="text-sm text-muted-foreground mb-3">
          Instead of deleting the <strong className="text-foreground">Data</strong>, delete the{" "}
          <strong className="text-foreground">Key</strong> required to read it.
        </p>

        <DataTable
          headers={["Step", "What Happens", "Result"]}
          rows={[
            ["Setup", "Each user (User_123) has a unique key (Key_123) in KMS", "Keys stored in Key Management Service"],
            ["Storage", "All PII for User_123 encrypted with Key_123 before storage", "Encrypted everywhere (DB, logs, backups)"],
            ["Delete Request", "User requests GDPR deletion", ""],
            ["Action", "Send command to KMS: DELETE Key_123", "Instant, no data scanning"],
            ["Result", "Data still exists but is mathematically unreadable", "Legally counts as Erasure"],
          ]}
        />

        <Pitfall>
          <strong>KMS Scale:</strong> Your KMS must handle millions of unique keys (one per user)
          with low latency. Every read request now requires a key fetch. Factor this into your
          architecture capacity planning.
        </Pitfall>
      </Subsection>

      <Subsection title="Envelope Encryption: Solving Key Rotation" color="amber">
        <p className="text-sm text-muted-foreground mb-4">
          PCI-DSS requires annual key rotation. But how do you rotate a key that encrypted 10
          million rows without locking the database?
        </p>

        <h4 className="text-sm font-semibold text-foreground mb-2">The Two-Key Hierarchy</h4>
        <DataTable
          headers={["Key Type", "Where It Lives", "Rotation Impact"]}
          rows={[
            [
              <strong key="kek">KEK (Key Encryption Key)</strong>,
              "Inside HSM, never leaves hardware",
              "Rotating KEK doesn't touch user data",
            ],
            [
              <strong key="dek">DEK (Data Encryption Key)</strong>,
              "Generated per user/batch, stored encrypted",
              "Encrypts actual user data",
            ],
          ]}
        />

        <h4 className="text-sm font-semibold text-foreground mb-2 mt-4">How It Works</h4>
        <div className="bg-muted/30 p-4 rounded-lg mb-4 font-mono text-sm">
          <p className="text-foreground">1. Generate random DEK</p>
          <p className="text-foreground">2. Encrypt Credit Card with DEK → Encrypted_Card</p>
          <p className="text-foreground">3. Ask HSM to encrypt DEK with KEK → Encrypted_DEK</p>
          <p className="text-foreground">4. Store: [Encrypted_Card, Encrypted_DEK] in DB row</p>
        </div>

        <h4 className="text-sm font-semibold text-foreground mb-2">Why This Solves Rotation</h4>
        <ul className="space-y-1">
          <BulletItem title="Rotating KEK">
            User data is encrypted with DEK (unchanged). You only re-encrypt the small DEKs, not 10M rows.
          </BulletItem>
          <BulletItem title="Employee Leaves">
            No human ever sees the raw AES key. They have IAM permissions to ask HSM to decrypt.
            Revoke the permission → instant. No re-encryption needed.
          </BulletItem>
        </ul>

        <InterviewTip>
          &quot;When Security demands key rotation, I don&apos;t panic about database locks.
          I ask: Are we using Envelope Encryption? Can we support multiple active KEK versions?
          Usually we&apos;re just revoking a user&apos;s IAM access, which is instant.&quot;
        </InterviewTip>
      </Subsection>

      <Subsection title="Lazy Migration (Read-Repair)" color="amber">
        <p className="text-sm text-muted-foreground mb-4">
          Even with Envelope Encryption, sometimes you must re-encrypt data (algorithm obsolete,
          DEK compromised). You never do this in one big batch.
        </p>

        <h4 className="text-sm font-semibold text-foreground mb-2">The Zero-Downtime Migration</h4>
        <DataTable
          headers={["Phase", "System Behavior", "Data State"]}
          rows={[
            [
              <span key="p1" className="text-blue-500 font-medium">1. Dual-Read</span>,
              "Install Key V2. Decrypt using V1 or V2. Encrypt new writes with V2.",
              "Mix of V1 and V2 encrypted data",
            ],
            [
              <span key="p2" className="text-green-500 font-medium">2. Lazy Migrate</span>,
              "User Aparna logs in. System fetches her V1 record, re-encrypts with V2, saves.",
              "Aparna now on V2",
            ],
            [
              <span key="p3" className="text-amber-500 font-medium">3. Natural Spread</span>,
              "Over 6 months, 80% of users log in and migrate naturally.",
              "80% V2, 20% V1 (dormant)",
            ],
            [
              <span key="p4" className="text-cyan-500 font-medium">4. Scavenger</span>,
              "Low-priority background job migrates remaining 20% (throttled).",
              "100% V2",
            ],
          ]}
        />

        <Insight title="Why Lazy Works">
          The compute cost is distributed over months of natural user traffic. You don&apos;t
          spike CPU (Bronze metric) or lock the database. Users never notice because re-encryption
          happens during their normal login flow.
        </Insight>
      </Subsection>

      <Subsection title="Payment Gateway SLOs" color="amber">
        <p className="text-sm text-muted-foreground mb-4">
          Payment systems have unique Gold Metrics. The most important thing for a user clicking
          &quot;Pay&quot; is <strong className="text-foreground">correctness</strong>, not just speed.
        </p>

        <DataTable
          headers={["Metric", "Definition", "Target", "Nuance"]}
          rows={[
            [
              <span key="avail" className="text-amber-500 font-bold">Availability</span>,
              "(2xx + 4xx) / Total Requests",
              "99.95%",
              "4xx counts as success (system rejected bad input)",
            ],
            [
              <span key="lat" className="text-amber-500 font-bold">Latency</span>,
              "Time to return token/success",
              "P99 < 500ms",
              "Payments should feel instant",
            ],
            [
              <span key="integrity" className="text-amber-500 font-bold">Correctness</span>,
              "User charged exactly once, exactly right amount",
              "100%",
              "No double charges, no wrong amounts",
            ],
          ]}
        />

        <h4 className="text-sm font-semibold text-foreground mb-2 mt-4">The Silver Metrics</h4>
        <ul className="space-y-1">
          <BulletItem title="Throughput (TPS)">
            Transactions Per Second. A sudden spike might be marketing push (good) or credential
            stuffing attack (bad).
          </BulletItem>
          <BulletItem title="DB Connection Pool">
            If connection pool hits 90%, next 100 users timeout. Leading indicator for Gold failure.
          </BulletItem>
        </ul>

        <InterviewTip>
          &quot;For a Payment Gateway, I define Gold metrics as: Did it work? (Availability),
          Was it fast? (Latency), and Was it correct? (Integrity). That last one—correctness—is
          what separates payments from other systems. A 500ms delay is annoying. A double charge
          is a lawsuit.&quot;
        </InterviewTip>
      </Subsection>

      <Subsection title="The &quot;Big Bang&quot; Anti-Pattern" color="amber">
        <p className="text-sm text-muted-foreground mb-4">
          A common failure in database migrations that a Principal TPM must catch during design review.
        </p>

        <h4 className="text-sm font-semibold text-foreground mb-2">The Scenario: Oracle to Postgres Migration</h4>
        <p className="text-sm text-muted-foreground mb-3">
          <strong className="text-foreground">Bad Plan:</strong> &quot;Saturday 2 AM, shut down
          Oracle, point DNS to Postgres, turn site back on. We have a backup if it fails.&quot;
        </p>

        <DataTable
          headers={["Risk", "Why It Fails", "Principal TPM Challenge"]}
          rows={[
            [
              "No Reverse Replication",
              "At 2:30 AM users buy $50K of goods. At 3 AM Postgres crashes. Oracle doesn't have those transactions.",
              "\"What is the backfill strategy for rollback?\"",
            ],
            [
              "DNS TTL",
              "DNS records cache for hours. Some users hit Oracle, some hit Postgres simultaneously.",
              "\"We need application-level routing, not DNS\"",
            ],
            [
              "Data In Flight",
              "Transactions in progress during cutover are lost or corrupted.",
              "\"How do we drain in-flight transactions?\"",
            ],
          ]}
        />

        <Insight title="The Correct Pattern">
          CDC (Change Data Capture) pipeline replicating from Postgres back to Oracle in real-time,
          so rollback target is always fresh. Feature Flag at application layer for instant traffic
          switch (not DNS). Dual-write period to verify consistency before cutover.
        </Insight>
      </Subsection>

      {/* Navigation */}
      <div className="mt-8 flex justify-between items-center pt-6 border-t border-border">
        <Link
          href="/nebula/system-design/deep-dives/compliance-governance"
          className="text-sm text-muted-foreground hover:text-primary"
        >
          &larr; Previous: Compliance & Data Governance
        </Link>
        <Link
          href="/nebula/system-design/deep-dives/risk-quantification"
          className="text-sm text-primary hover:underline"
        >
          Next: Risk Quantification &rarr;
        </Link>
      </div>
    </SystemDesignLayout>
  );
}
