"use client";

/**
 * Claude AI - Capstone Project Proposals
 *
 * 5 AI/TPM capstone projects generated using Claude
 * Focuses on intelligent systems, orchestration, and AI governance
 */

import Link from "next/link";
import { CapstoneLayout } from "@/components/CapstoneLayout";

interface ClaudeProject {
  id: string;
  number: number;
  title: string;
  summary: string;
  tags: { label: string; type: "telecom" | "enterprise" | "consumer" | "infra" | "ai" }[];
}

const claudeProjects: ClaudeProject[] = [
  {
    id: "capacity-planning",
    number: 1,
    title: "Intelligent Capacity Planning System",
    summary: "AI-powered infrastructure capacity forecasting that predicts resource needs using ML models, preventing bottlenecks and optimizing cloud spend across distributed systems.",
    tags: [
      { label: "Infrastructure", type: "infra" },
      { label: "AI/ML", type: "ai" },
      { label: "Platform TPM", type: "enterprise" },
    ],
  },
  {
    id: "journey-orchestration",
    number: 2,
    title: "Customer Journey Orchestration Engine",
    summary: "Event-driven platform that dynamically orchestrates personalized customer experiences across channels using real-time behavioral signals and predictive analytics.",
    tags: [
      { label: "Product TPM", type: "enterprise" },
      { label: "AI/ML", type: "ai" },
      { label: "Consumer", type: "consumer" },
    ],
  },
  {
    id: "fraud-detection",
    number: 3,
    title: "Real-time Fraud Detection Platform",
    summary: "Streaming analytics system that identifies fraudulent transactions using ensemble ML models, graph analysis, and behavioral anomaly detection at scale.",
    tags: [
      { label: "Enterprise", type: "enterprise" },
      { label: "AI/ML TPM", type: "ai" },
      { label: "Trust & Safety", type: "infra" },
    ],
  },
  {
    id: "developer-experience",
    number: 4,
    title: "Developer Experience Platform",
    summary: "Unified internal developer portal with AI-assisted code generation, automated documentation, and intelligent CI/CD workflows to accelerate engineering velocity.",
    tags: [
      { label: "Platform TPM", type: "infra" },
      { label: "DevOps", type: "enterprise" },
      { label: "AI/ML", type: "ai" },
    ],
  },
  {
    id: "model-governance",
    number: 5,
    title: "AI Model Governance & Registry",
    summary: "Enterprise-grade ML model lifecycle management system with versioning, A/B testing, monitoring, and compliance controls for responsible AI deployment.",
    tags: [
      { label: "AI/ML TPM", type: "ai" },
      { label: "Platform", type: "infra" },
      { label: "Governance", type: "enterprise" },
    ],
  },
];

const tagStyles: Record<string, string> = {
  telecom: "bg-green-500/15 text-green-600 dark:text-green-400",
  enterprise: "bg-blue-500/15 text-blue-600 dark:text-blue-400",
  consumer: "bg-orange-500/15 text-orange-600 dark:text-orange-400",
  infra: "bg-purple-500/15 text-purple-600 dark:text-purple-400",
  ai: "bg-pink-500/15 text-pink-600 dark:text-pink-400",
};

function ClaudeContent() {
  return (
    <div className="max-w-[1100px] mx-auto">
      <Link
        href="/nebula/capstone"
        className="inline-flex items-center gap-2 text-muted-foreground hover:text-primary text-sm mb-6 transition-colors"
      >
        ← Back to All Projects
      </Link>

      {/* Header */}
      <header className="mb-8 p-6 bg-card rounded-xl border border-border shadow-sm">
        <div className="flex items-center gap-4 mb-4">
          <div
            className="w-14 h-14 rounded-xl flex items-center justify-center text-2xl font-bold"
            style={{
              background: "linear-gradient(135deg, #CC9B7A 0%, #D4A574 100%)",
              color: "#1a1a1a",
            }}
          >
            C
          </div>
          <div>
            <h1 className="text-2xl font-bold text-foreground">Claude Projects</h1>
            <span className="text-sm text-muted-foreground">5 projects</span>
          </div>
        </div>
        <p className="text-muted-foreground">
          AI/TPM capstone projects generated by Claude, focusing on intelligent systems,
          orchestration engines, and enterprise AI governance
        </p>
      </header>

      {/* Project Cards */}
      <section className="mb-8">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {claudeProjects.map((project) => (
            <Link
              key={project.id}
              href={`/nebula/capstone/claude/${project.id}`}
              className="block p-5 bg-card rounded-xl border border-border hover:border-primary/50 hover:shadow-md transition-all"
            >
              <div className="flex items-center gap-3 mb-3">
                <span
                  className="w-8 h-8 rounded-full flex items-center justify-center text-white text-sm font-bold flex-shrink-0"
                  style={{ backgroundColor: "#cc785c" }}
                >
                  {project.number}
                </span>
                <h2 className="font-semibold text-foreground">{project.title}</h2>
              </div>
              <p className="text-sm text-muted-foreground mb-4 line-clamp-2">
                {project.summary}
              </p>
              <div className="flex flex-wrap gap-2">
                {project.tags.map((tag) => (
                  <span
                    key={tag.label}
                    className={`px-2.5 py-1 rounded-md text-xs font-medium ${tagStyles[tag.type]}`}
                  >
                    {tag.label}
                  </span>
                ))}
              </div>
            </Link>
          ))}
        </div>
      </section>

      {/* Claude's Approach */}
      <div className="p-5 bg-muted/30 rounded-xl border border-border mb-8">
        <h3 className="text-lg font-semibold text-primary mb-3">
          Claude's Approach
        </h3>
        <p className="text-muted-foreground text-sm leading-relaxed">
          Claude's project suggestions emphasize sophisticated system design, real-time data processing,
          and enterprise-grade governance. These projects showcase expertise in building intelligent platforms
          that combine ML capabilities with robust infrastructure, making them ideal for Senior TPM roles
          focused on AI/ML product development and platform engineering at scale.
        </p>
      </div>

      {/* Navigation */}
      <div className="text-center">
        <Link
          href="/nebula/capstone/comparison"
          className="inline-flex items-center gap-2 text-primary hover:underline text-sm"
        >
          Compare All LLM Suggestions →
        </Link>
      </div>

      {/* Footer */}
      <footer className="text-center py-6 mt-8 border-t border-border text-muted-foreground text-sm">
        Generated by Claude AI | Part of Nebula Capstone Project Collection
      </footer>
    </div>
  );
}

export default function ClaudeProjectsPage() {
  return (
    <CapstoneLayout
      title="Claude - Capstone Projects"
      description="AI/TPM capstone projects generated by Claude AI"
      currentLLM="claude"
    >
      <ClaudeContent />
    </CapstoneLayout>
  );
}
