import Link from "next/link";
import { TelcoOpsDocsLayout } from "@/components/TelcoOpsDocsLayout";

export const metadata = {
  title: "Scope Boundaries | TelcoOps",
  description: "What TelcoOps deliberately does not do, and why.",
};

export default function TelcoOpsScopeBoundariesPage() {
  return (
    <TelcoOpsDocsLayout>
      <article className="prose prose-slate max-w-none dark:prose-invert">
        <h1>Scope Boundaries</h1>

        <p className="lead">
          What TelcoOps deliberately does not do. Each exclusion is a conscious decision, not a gap. Defining what is out of scope
          is as important as defining what is in scope -- it prevents scope creep and sets clear expectations with stakeholders.
        </p>

        <hr />

        <h2>1. Not an Automated Remediation System</h2>

        <p>
          TelcoOps generates RCA hypotheses. It does <strong>not</strong> execute runbooks, trigger rollbacks, or take any
          remediation action. The design principle is explicit: <em>AI suggests, human decides, system audits</em>.
        </p>

        <p>
          Every RCA artifact defaults to <code>pending_review</code> status. An operator must explicitly accept or reject
          the hypothesis before any action is taken. This boundary exists because the blast radius of wrong automated remediation
          in a telecom NOC is measured in customer-minutes.
        </p>

        <div className="not-prose my-6 overflow-x-auto">
          <table className="w-full border-collapse text-sm">
            <thead>
              <tr className="border-b border-border bg-muted/50">
                <th className="px-4 py-3 text-left font-semibold">Capability</th>
                <th className="px-4 py-3 text-left font-semibold">In Scope</th>
                <th className="px-4 py-3 text-left font-semibold">Out of Scope</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b border-border"><td className="px-4 py-3">RCA hypothesis generation</td><td className="px-4 py-3">Yes</td><td className="px-4 py-3">-</td></tr>
              <tr className="border-b border-border"><td className="px-4 py-3">Confidence scoring</td><td className="px-4 py-3">Yes</td><td className="px-4 py-3">-</td></tr>
              <tr className="border-b border-border"><td className="px-4 py-3">Evidence packaging</td><td className="px-4 py-3">Yes</td><td className="px-4 py-3">-</td></tr>
              <tr className="border-b border-border"><td className="px-4 py-3">Runbook execution</td><td className="px-4 py-3">-</td><td className="px-4 py-3">Phase 3+</td></tr>
              <tr className="border-b border-border"><td className="px-4 py-3">Automated rollback</td><td className="px-4 py-3">-</td><td className="px-4 py-3">Out of scope</td></tr>
              <tr className="border-b border-border"><td className="px-4 py-3">Ticket creation</td><td className="px-4 py-3">-</td><td className="px-4 py-3">Webhook stubs only</td></tr>
            </tbody>
          </table>
        </div>

        <hr />

        <h2>2. Not a Production Monitoring Tool</h2>

        <p>
          TelcoOps uses synthetic data generated by a deterministic scenario engine. It does <strong>not</strong> ingest
          live alerts from Prometheus, PagerDuty, Datadog, or any production monitoring system.
        </p>

        <p>
          The synthetic generator supports 11 incident types with configurable alert rates, noise levels, and deterministic seeds.
          This enables repeatable evaluation runs -- the same seed always produces the same alerts, the same incidents, and
          the same ground truth for scoring.
        </p>

        <p>
          Integration with production monitoring is a Phase 2+ feature. The webhook stubs for ServiceNow and Jira demonstrate
          the integration pattern without requiring live infrastructure.
        </p>

        <hr />

        <h2>3. Not Multi-Tenant</h2>

        <p>
          Tenant ID fields exist on all three data models (Alert, Incident, RCA Artifact). The API supports optional
          <code>X-Tenant-Id</code> headers and <code>REQUIRE_TENANT_ID</code> configuration. However, true multi-tenant
          isolation is not enforced.
        </p>

        <ul>
          <li>No row-level security in SQLite.</li>
          <li>No tenant-scoped RBAC or permission model.</li>
          <li>No tenant-specific rate limiting or quotas.</li>
        </ul>

        <p>
          The schema is tenant-aware by design so that the migration to multi-tenancy is additive, not a rewrite.
          Production rollout would require PostgreSQL with row-level security and a proper identity provider.
        </p>

        <hr />

        <h2>4. Not ML-Model-Based</h2>

        <p>
          TelcoOps uses an LLM (Gemini or Tele-LLM) with RAG context for RCA generation. It does <strong>not</strong> use
          trained ML models, and there is no model training pipeline.
        </p>

        <div className="not-prose my-6 overflow-x-auto">
          <table className="w-full border-collapse text-sm">
            <thead>
              <tr className="border-b border-border bg-muted/50">
                <th className="px-4 py-3 text-left font-semibold">ML Capability</th>
                <th className="px-4 py-3 text-left font-semibold">Status</th>
                <th className="px-4 py-3 text-left font-semibold">When Addressed</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b border-border"><td className="px-4 py-3">LLM-based RCA</td><td className="px-4 py-3">Implemented</td><td className="px-4 py-3">Phase 1 (current)</td></tr>
              <tr className="border-b border-border"><td className="px-4 py-3">RAG retrieval</td><td className="px-4 py-3">Implemented</td><td className="px-4 py-3">Phase 1 (current)</td></tr>
              <tr className="border-b border-border"><td className="px-4 py-3">Semantic evaluation</td><td className="px-4 py-3">Implemented</td><td className="px-4 py-3">Phase 1 (current)</td></tr>
              <tr className="border-b border-border"><td className="px-4 py-3">Model training pipeline</td><td className="px-4 py-3">Not started</td><td className="px-4 py-3">Phase 2</td></tr>
              <tr className="border-b border-border"><td className="px-4 py-3">Drift detection</td><td className="px-4 py-3">Not started</td><td className="px-4 py-3">Phase 3</td></tr>
              <tr className="border-b border-border"><td className="px-4 py-3">Fine-tuned incident classifier</td><td className="px-4 py-3">Not started</td><td className="px-4 py-3">Phase 3</td></tr>
            </tbody>
          </table>
        </div>

        <hr />

        <h2>5. Not Compliance-Certified</h2>

        <p>
          TelcoOps is a demo with security-aware architecture, not a compliance-certified system.
        </p>

        <ul>
          <li>Optional API tokens (three-tier: api_token, admin_token, metrics_token) but no encryption at rest.</li>
          <li>No PII in synthetic data, but no PII detection or redaction pipeline.</li>
          <li>Audit trail exists (audit_log.jsonl) but is not tamper-proof.</li>
          <li>No SOC 2, HIPAA, or PCI DSS compliance claims.</li>
        </ul>

        <p>
          Production rollout would require: encryption at rest, TLS everywhere, proper secret management, audit log
          integrity (append-only with checksums), and a formal compliance review.
        </p>

        <hr />

        <div className="not-prose my-6 rounded-lg border-2 border-blue-500/30 bg-blue-500/5 p-4">
          <p className="text-sm font-semibold text-blue-700 dark:text-blue-400 mb-2">Design Principle</p>
          <p className="text-sm">
            An RCA platform that tries to automate everything earns no operator trust. Scope boundaries are not limitations --
            they are decisions that preserve focus, build trust, and create a clear upgrade path.
          </p>
        </div>

        <hr />

        <p className="text-sm text-muted-foreground">
          Next: <Link href="/docs/telcoops/failure-modes" className="text-primary hover:underline">Failure Modes</Link>
        </p>
      </article>
    </TelcoOpsDocsLayout>
  );
}
