"use client";

/**
 * Knowledge Base - Professor Gemini Generated Guides
 *
 * Documents generated by Professor Gemini (gemini-responses folder)
 * Features a sidebar TOC for quick navigation between documents
 * Mobile responsive with collapsible sidebar
 */

import { useState, useEffect, useRef, useMemo } from "react";
import Link from "next/link";
import { useSearchParams, useRouter } from "next/navigation";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { AuthGate } from "@/components/AuthGate";
import { SidebarCollapseButton } from "@/components/SidebarCollapseButton";
import { PageMinimap } from "@/components/PageMinimap";
import { knowledgeBaseDocs } from "@/data/knowledge-base";
import {
  knowledgeBaseWikiDoc,
  knowledgeBaseWikiSections,
  allWikiDocs,
  wikiAwsDoc,
  wikiGcpDoc,
  wikiAzureDoc,
  wikiCrossCloudDoc,
  isWikiSlug,
  getWikiSectionsForSlug,
  type AdoptionLevel,
  type KnowledgeBaseWikiEntry,
  type KnowledgeBaseWikiSection,
} from "@/data/knowledge-base-wiki";
import mermaid from "mermaid";

// Extract headings from markdown for TOC
interface TocItem {
  id: string;
  text: string;
  level: number;
}

function slugifyHeading(text: string) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-");
}

// Part I: Strategy & Business Physics [1.1-1.4]
const CLOUD_ECONOMICS_ORDER = [
  "cloud-economics-finops",
  "cost-model-fundamentals",
  "capex-vs-opex-mental-model",
  "reserved-vs-spot-strategy",
  "data-transfer-optimization",
];

const SLA_MATHEMATICS_ORDER = [
  "sla-mathematics-reliability",
  "sloslasli-precision-matters",
  "composite-sla-calculation",
  "error-budgets-practical-application",
  "availability-tiers-reality-check",
];

const COMPLIANCE_ORDER = [
  "compliance-data-sovereignty",
  "data-classification-framework",
  "gdpr-what-you-must-know",
  "pci-dss-for-payment-systems",
  "soc-2-trust-framework",
];

const RISK_QUANTIFICATION_ORDER = [
  "risk-quantification",
  "expected-loss-calculation",
  "blast-radius-analysis",
  "technical-debt-quantification",
];

// Part II: Core Infrastructure [2.1-2.6]
const SCALING_ARCHITECTURE_ORDER = [
  "scaling-architecture",
  "vertical-scaling-limits",
  "horizontal-scaling-patterns",
  "auto-scaling-strategies",
];

const NETWORKING_TRAFFIC_ORDER = [
  "protocol-fundamentals",
  "dns-architecture",
  "load-balancing-deep-dive",
  "content-delivery-networks-cdn",
];

const DATABASE_DEEP_DIVE_ORDER = [
  "sql-vs-nosql-the-real-trade-offs",
  "cap-theorem-practical-understanding",
  "replication-patterns",
  "database-sharding-strategies",
];

const MIGRATION_PATTERNS_ORDER = [
  "strangler-fig-pattern",
  "branch-by-abstraction",
  "dual-write-dual-read-pattern",
  "change-data-capture-cdc",
];

const COMMUNICATION_PATTERNS_ORDER = [
  "synchronous-rest-vs-grpc-vs-graphql",
  "asynchronous-queues-vs-pubsub",
  "real-time-polling-vs-websockets",
  "idempotency-critical-concept",
];

// Part III: Advanced & AI [3.1-3.7]
const DISTRIBUTED_CONSENSUS_ORDER = [
  "the-consensus-problem",
  "leader-election",
  "paxos-and-raft",
];

const GLOBAL_ARCHITECTURE_ORDER = [
  "latency-physics",
  "geo-routing",
  "multi-region-patterns",
];

const RESILIENCY_PATTERNS_ORDER = [
  "retry-strategies",
  "circuit-breaker",
  "bulkhead-pattern",
  "backpressure",
  "chaos-engineering",
];

const PROBABILISTIC_DATA_STRUCTURES_ORDER = [
  "bloom-filters",
  "hyperloglog-hll",
  "count-min-sketch",
  "trade-offs-summary",
];

const AI_ML_INFRASTRUCTURE_ORDER = [
  "training-vs-inference",
  "data-architecture-patterns",
  "mlops-pipeline",
  "llm-serving-considerations",
  "vector-databases-and-rag",
];

const OBSERVABILITY_ORDER = [
  "the-three-pillars-deep-dive",
  "the-golden-signals-google-sre",
  "distributed-tracing-architecture",
  "alerting-best-practices",
];

const SECURITY_ARCHITECTURE_ORDER = [
  "authentication-vs-authorization",
  "zero-trust-architecture",
  "encryption-strategy",
  "api-security",
];

// Helper to filter and sort docs by the specified order
function getOrderedDocs(
  docs: typeof knowledgeBaseDocs,
  orderArray: string[]
): typeof knowledgeBaseDocs {
  const orderSet = new Set(orderArray);
  const filtered = docs.filter((doc) => orderSet.has(doc.slug));
  return filtered.sort(
    (a, b) => orderArray.indexOf(a.slug) - orderArray.indexOf(b.slug)
  );
}



function extractHeadings(markdown: string): TocItem[] {
  const headingRegex = /^(#{2,3})\s+(.+)$/gm;
  const headings: TocItem[] = [];
  let match;

  while ((match = headingRegex.exec(markdown)) !== null) {
    const level = match[1].length;
    const text = match[2].trim();
    // Create slug from heading text
    const id = text
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, "")
      .replace(/\s+/g, "-")
      .replace(/-+/g, "-");
    headings.push({ id, text, level });
  }

  return headings;
}

// Remove duplicate titles and section headers
function stripDuplicateTitle(content: string, title: string): string {
  let processed = content;

  // 1. Remove first H1 if it matches the document title
  const h1Match = processed.match(/^#\s+(.+)\n/);
  if (h1Match) {
    const h1Text = h1Match[1].trim();
    if (h1Text.toLowerCase() === title.toLowerCase() ||
        h1Text.toLowerCase().includes(title.toLowerCase()) ||
        title.toLowerCase().includes(h1Text.toLowerCase())) {
      processed = processed.replace(/^#\s+.+\n+/, "");
    }
  }

  // 2. Remove H1 section headers that appear after *** separators
  processed = processed.replace(/\n\*{3}\n+#\s+[IVXLCDM]+\.[^\n]+\n/g, "\n***\n\n");

  // 3. Remove duplicate headings throughout the document
  // Professor Gemini content has intro sections with brief H2 summaries,
  // then detailed sections with the same H2 titles - remove the brief intro ones
  // Important: Only compare headings at the SAME level (e.g., H2 vs H2, not H2 vs H3)
  const lines = processed.split("\n");
  const seenHeadings = new Map<string, number>(); // "level:heading text" -> line index
  const linesToRemove = new Set<number>();

  // First pass: identify all headings and find duplicates at the same level
  lines.forEach((line, index) => {
    const headingMatch = line.match(/^(#{1,3})\s+(.+)$/);
    if (headingMatch) {
      const level = headingMatch[1].length;
      const headingText = headingMatch[2].trim().toLowerCase();
      // Use level + text as key to only detect same-level duplicates
      const key = `${level}:${headingText}`;

      if (seenHeadings.has(key)) {
        // Found a duplicate at the same level - determine which one to remove
        const firstIndex = seenHeadings.get(key)!;

        // Check content length after each heading to decide which to keep
        // Keep the one with more content (the detailed section)
        const contentAfterFirst = getContentLengthAfterHeading(lines, firstIndex);
        const contentAfterCurrent = getContentLengthAfterHeading(lines, index);

        if (contentAfterFirst < contentAfterCurrent) {
          // First one has less content - it's likely the intro summary, remove it
          linesToRemove.add(firstIndex);
          seenHeadings.set(key, index); // Update to keep track of the better one
        } else {
          // Current one has less or equal content - remove it
          linesToRemove.add(index);
        }
      } else {
        seenHeadings.set(key, index);
      }
    }
  });

  // Second pass: rebuild content without duplicate headings
  processed = lines
    .filter((_, index) => !linesToRemove.has(index))
    .join("\n");

  // Clean up excessive blank lines
  processed = processed.replace(/\n{4,}/g, "\n\n\n");

  return processed;
}

// Helper: estimate content length after a heading until next heading or separator
function getContentLengthAfterHeading(lines: string[], headingIndex: number): number {
  let length = 0;
  for (let i = headingIndex + 1; i < lines.length && i < headingIndex + 50; i++) {
    const line = lines[i];
    // Stop at next heading or separator
    if (line.match(/^#{1,3}\s+/) || line.match(/^\*{3}$/)) {
      break;
    }
    length += line.length;
  }
  return length;
}

// Back to Top Button Component
function BackToTopButton() {
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    const toggleVisibility = () => {
      setIsVisible(window.scrollY > 400);
    };

    window.addEventListener("scroll", toggleVisibility);
    return () => window.removeEventListener("scroll", toggleVisibility);
  }, []);

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  if (!isVisible) return null;

  return (
    <button
      onClick={scrollToTop}
      className="fixed bottom-6 right-6 z-40 p-3 rounded-full bg-primary text-primary-foreground shadow-lg hover:bg-primary/90 transition-all hover:scale-110"
      aria-label="Back to top"
    >
      <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 10l7-7m0 0l7 7m-7-7v18" />
      </svg>
    </button>
  );
}

// Table of Contents Component - Roman numeral sections only
function TableOfContents({ headings, activeId }: { headings: TocItem[]; activeId: string }) {
  if (headings.length === 0) return null;

  // Only show H2 Roman numeral section headers (I., II., III., IV., V., etc.)
  // Exclude H3 sub-headers (like Interview Questions subsections)
  const romanPattern = /^[IVXLCDM]+\.\s+/i;
  const romanHeadings = headings.filter(h => h.level === 2 && romanPattern.test(h.text));
  if (romanHeadings.length === 0) return null;

  return (
    <nav className="mb-8 p-4 rounded-lg border border-border bg-muted/30">
      <div className="flex items-center gap-2 mb-3 text-sm font-semibold text-foreground">
        <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 10h16M4 14h16M4 18h16" />
        </svg>
        Contents
      </div>
      <div className="flex flex-wrap gap-2">
        {romanHeadings.map((heading, index) => (
          <a
            key={`${heading.id}-${index}`}
            href={`#${heading.id}`}
            className={`inline-block px-3 py-1.5 text-xs rounded-full border transition-colors hover:bg-primary/10 hover:text-primary hover:border-primary/50 ${
              activeId === heading.id
                ? "bg-primary/10 text-primary border-primary/50 font-medium"
                : "text-muted-foreground border-border"
            }`}
            onClick={(e) => {
              e.preventDefault();
              const element = document.getElementById(heading.id);
              if (element) {
                element.scrollIntoView({ behavior: "smooth" });
              }
            }}
          >
            {heading.text.length > 40 ? heading.text.slice(0, 40) + "..." : heading.text}
          </a>
        ))}
      </div>
    </nav>
  );
}

// Initialize mermaid with dark mode support
mermaid.initialize({
  startOnLoad: false,
  theme: "neutral",
  securityLevel: "loose",
  fontFamily: "inherit",
});

function formatDate(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

// Fullscreen Modal for Mermaid diagrams
function DiagramModal({ chart, onClose }: { chart: string; onClose: () => void }) {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (containerRef.current) {
      const id = `mermaid-modal-${Math.random().toString(36).substring(2, 9)}`;
      containerRef.current.innerHTML = "";

      mermaid
        .render(id, chart)
        .then(({ svg }) => {
          if (containerRef.current) {
            containerRef.current.innerHTML = svg;
            // Scale SVG to fill available space
            const svgEl = containerRef.current.querySelector("svg");
            if (svgEl) {
              // Remove fixed dimensions and let it scale
              svgEl.removeAttribute("height");
              svgEl.style.width = "100%";
              svgEl.style.height = "auto";
              svgEl.style.maxHeight = "calc(100vh - 120px)";
              svgEl.style.minWidth = "min(100%, 800px)";
            }
          }
        })
        .catch((error) => {
          console.error("Mermaid render error:", error);
          if (containerRef.current) {
            containerRef.current.innerHTML = `<pre class="text-red-500">Diagram error: ${error.message}</pre>`;
          }
        });
    }
  }, [chart]);

  // Close on Escape key
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [onClose]);

  // Prevent body scroll when modal is open
  useEffect(() => {
    document.body.style.overflow = "hidden";
    return () => { document.body.style.overflow = ""; };
  }, []);

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 backdrop-blur-sm"
      onClick={onClose}
    >
      {/* Close button - fixed position */}
      <button
        onClick={onClose}
        className="fixed top-4 right-4 p-3 rounded-full bg-white/10 hover:bg-white/20 transition-colors z-50 text-white"
        aria-label="Close"
      >
        <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>

      {/* Hint - fixed position */}
      <div className="fixed top-5 left-1/2 -translate-x-1/2 text-sm text-white/60">
        Press ESC or click outside to close
      </div>

      {/* Diagram container - full width */}
      <div
        className="w-[95vw] h-[90vh] bg-white rounded-2xl shadow-2xl overflow-auto flex items-center justify-center p-8"
        onClick={(e) => e.stopPropagation()}
      >
        <div ref={containerRef} className="w-full h-full flex items-center justify-center" />
      </div>
    </div>
  );
}

// Mermaid diagram component
function MermaidDiagram({ chart }: { chart: string }) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [isExpanded, setIsExpanded] = useState(false);

  useEffect(() => {
    if (containerRef.current) {
      const id = `mermaid-${Math.random().toString(36).substring(2, 9)}`;
      containerRef.current.innerHTML = "";

      mermaid
        .render(id, chart)
        .then(({ svg }) => {
          if (containerRef.current) {
            containerRef.current.innerHTML = svg;
          }
        })
        .catch((error) => {
          console.error("Mermaid render error:", error);
          if (containerRef.current) {
            containerRef.current.innerHTML = `<pre class="text-red-500">Diagram error: ${error.message}</pre>`;
          }
        });
    }
  }, [chart]);

  return (
    <>
      <div
        ref={containerRef}
        onClick={() => setIsExpanded(true)}
        className="my-6 flex justify-center overflow-x-auto cursor-zoom-in group relative rounded-lg border border-transparent hover:border-primary/30 hover:bg-primary/5 transition-all p-2"
        title="Click to expand"
      />
      {isExpanded && <DiagramModal chart={chart} onClose={() => setIsExpanded(false)} />}
    </>
  );
}

// Custom code block renderer
function CodeBlock({
  className,
  children,
}: {
  className?: string;
  children?: React.ReactNode;
}) {
  const match = /language-(\w+)/.exec(className || "");
  const language = match ? match[1] : "";
  const code = String(children).replace(/\n$/, "");

  if (language === "mermaid") {
    return <MermaidDiagram chart={code} />;
  }

  return (
    <code
      className={`${className || ""} font-mono text-sm`}
      style={{ fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace" }}
    >
      {children}
    </code>
  );
}

// Adoption level badge colors and labels
const adoptionConfig: Record<AdoptionLevel, { label: string; bg: string; text: string; border: string }> = {
  universal: { label: "Universal", bg: "bg-emerald-500/10", text: "text-emerald-600 dark:text-emerald-400", border: "border-emerald-500/30" },
  standard: { label: "Standard", bg: "bg-blue-500/10", text: "text-blue-600 dark:text-blue-400", border: "border-blue-500/30" },
  high: { label: "High", bg: "bg-purple-500/10", text: "text-purple-600 dark:text-purple-400", border: "border-purple-500/30" },
  common: { label: "Common", bg: "bg-amber-500/10", text: "text-amber-600 dark:text-amber-400", border: "border-amber-500/30" },
  selective: { label: "Selective", bg: "bg-cyan-500/10", text: "text-cyan-600 dark:text-cyan-400", border: "border-cyan-500/30" },
  emerging: { label: "Emerging", bg: "bg-pink-500/10", text: "text-pink-600 dark:text-pink-400", border: "border-pink-500/30" },
  legacy: { label: "Legacy", bg: "bg-gray-500/10", text: "text-gray-500 dark:text-gray-400", border: "border-gray-500/30" },
};

// Cost tier indicator
const costTierConfig: Record<string, { icon: string; label: string }> = {
  low: { icon: "$", label: "Low cost" },
  medium: { icon: "$$", label: "Medium cost" },
  high: { icon: "$$$", label: "High cost" },
  variable: { icon: "~$", label: "Variable cost" },
};

function AdoptionBadge({ level }: { level: AdoptionLevel }) {
  const config = adoptionConfig[level];
  return (
    <span className={`inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-semibold uppercase tracking-wider ${config.bg} ${config.text} border ${config.border}`}>
      {config.label}
    </span>
  );
}

function CostIndicator({ tier }: { tier?: "low" | "medium" | "high" | "variable" }) {
  if (!tier) return null;
  const config = costTierConfig[tier];
  return (
    <span
      className="inline-flex items-center justify-center w-8 h-5 rounded text-[10px] font-mono font-bold bg-muted text-muted-foreground"
      title={config.label}
    >
      {config.icon}
    </span>
  );
}

function ToolRow({ entry, isExpanded, onToggle, providerColor }: {
  entry: KnowledgeBaseWikiEntry;
  isExpanded: boolean;
  onToggle: () => void;
  providerColor: string;
}) {
  return (
    <>
      <tr
        onClick={onToggle}
        className={`cursor-pointer transition-colors ${isExpanded ? "bg-muted/40" : "hover:bg-muted/20"}`}
      >
        <td className="px-4 py-3">
          <div className="flex items-center gap-3">
            <span
              className="w-1 h-8 rounded-full flex-shrink-0"
              style={{ backgroundColor: providerColor }}
            />
            <div>
              <div className="font-semibold text-foreground">{entry.tool}</div>
              <div className="text-xs text-muted-foreground mt-0.5 line-clamp-1 sm:hidden">
                {entry.summary}
              </div>
            </div>
          </div>
        </td>
        <td className="px-4 py-3 text-muted-foreground hidden sm:table-cell">
          <div className="line-clamp-2">{entry.summary}</div>
        </td>
        <td className="px-4 py-3 hidden lg:table-cell">
          <div className="flex items-center gap-2">
            <AdoptionBadge level={entry.adoption} />
            <CostIndicator tier={entry.costTier} />
          </div>
        </td>
        <td className="px-4 py-3 w-8">
          <svg
            className={`h-4 w-4 text-muted-foreground transition-transform ${isExpanded ? "rotate-180" : ""}`}
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
          </svg>
        </td>
      </tr>
      {isExpanded && (
        <tr className="bg-muted/20">
          <td colSpan={4} className="px-4 py-4">
            <div className="pl-4 border-l-2 space-y-3" style={{ borderColor: providerColor }}>
              {/* Mobile: show summary */}
              <div className="sm:hidden">
                <div className="text-xs font-medium text-muted-foreground uppercase tracking-wider mb-1">Summary</div>
                <p className="text-sm text-foreground">{entry.summary}</p>
              </div>
              {/* Mobile: show adoption badges */}
              <div className="lg:hidden">
                <div className="text-xs font-medium text-muted-foreground uppercase tracking-wider mb-1">Adoption</div>
                <div className="flex items-center gap-2">
                  <AdoptionBadge level={entry.adoption} />
                  <CostIndicator tier={entry.costTier} />
                </div>
              </div>
              {/* Mag7 Signal */}
              <div>
                <div className="text-xs font-medium text-muted-foreground uppercase tracking-wider mb-1">Mag7 Signal</div>
                <p className="text-sm text-foreground">{entry.mag7}</p>
              </div>
              {/* Decision Context - Principal TPM Focus */}
              {entry.decision && (
                <div>
                  <div className="text-xs font-medium text-primary uppercase tracking-wider mb-1 flex items-center gap-1.5">
                    <svg className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    Decision Context
                  </div>
                  <p className="text-sm text-foreground">{entry.decision}</p>
                </div>
              )}
            </div>
          </td>
        </tr>
      )}
    </>
  );
}

function WikiTables({ sections, title, subtitle }: {
  sections: KnowledgeBaseWikiSection[];
  title?: string;
  subtitle?: string;
}) {
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedProvider, setSelectedProvider] = useState<string | null>(null);
  const [selectedAdoption, setSelectedAdoption] = useState<AdoptionLevel | null>(null);
  const [expandedTools, setExpandedTools] = useState<Set<string>>(new Set());

  const totalTools = sections.reduce(
    (sum, section) =>
      sum + section.groups.reduce((groupSum, group) => groupSum + group.entries.length, 0),
    0
  );

  // Only show provider filter if there are multiple providers
  const showProviderFilter = sections.length > 1;

  // Filter logic
  const filteredSections = useMemo(() => {
    return sections
      .filter((section) => !selectedProvider || section.provider === selectedProvider)
      .map((section) => ({
        ...section,
        groups: section.groups
          .map((group) => ({
            ...group,
            entries: group.entries.filter((entry) => {
              const matchesSearch =
                !searchQuery ||
                entry.tool.toLowerCase().includes(searchQuery.toLowerCase()) ||
                entry.summary.toLowerCase().includes(searchQuery.toLowerCase()) ||
                entry.mag7.toLowerCase().includes(searchQuery.toLowerCase()) ||
                (entry.decision && entry.decision.toLowerCase().includes(searchQuery.toLowerCase()));
              const matchesAdoption = !selectedAdoption || entry.adoption === selectedAdoption;
              return matchesSearch && matchesAdoption;
            }),
          }))
          .filter((group) => group.entries.length > 0),
      }))
      .filter((section) => section.groups.length > 0);
  }, [searchQuery, selectedProvider, selectedAdoption]);

  const filteredToolCount = filteredSections.reduce(
    (sum, section) =>
      sum + section.groups.reduce((groupSum, group) => groupSum + group.entries.length, 0),
    0
  );

  const toggleTool = (toolId: string) => {
    setExpandedTools((prev) => {
      const next = new Set(prev);
      if (next.has(toolId)) {
        next.delete(toolId);
      } else {
        next.add(toolId);
      }
      return next;
    });
  };

  const clearFilters = () => {
    setSearchQuery("");
    setSelectedProvider(null);
    setSelectedAdoption(null);
  };

  const hasActiveFilters = searchQuery || selectedProvider || selectedAdoption;

  return (
    <div className="space-y-6">
      {/* Search and Filters */}
      <div className="sticky top-0 z-10 bg-background/95 backdrop-blur-sm py-4 -mx-4 px-4 sm:-mx-6 sm:px-6 border-b border-border">
        <div className="flex flex-col sm:flex-row gap-3">
          {/* Search Input */}
          <div className="relative flex-1">
            <svg
              className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
            <input
              type="text"
              placeholder="Search tools, features, or trade-offs..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-10 pr-4 py-2.5 rounded-lg border border-border bg-background text-sm placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary"
            />
            {searchQuery && (
              <button
                onClick={() => setSearchQuery("")}
                className="absolute right-3 top-1/2 -translate-y-1/2 p-1 hover:bg-muted rounded"
              >
                <svg className="h-3 w-3 text-muted-foreground" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            )}
          </div>

          {/* Provider Filter - only show when multiple providers */}
          {showProviderFilter && (
            <div className="flex gap-2 overflow-x-auto pb-1 sm:pb-0">
              <button
                onClick={() => setSelectedProvider(null)}
                className={`px-3 py-2 rounded-lg text-xs font-medium whitespace-nowrap transition-colors ${
                  !selectedProvider
                    ? "bg-primary text-primary-foreground"
                    : "bg-muted text-muted-foreground hover:text-foreground"
                }`}
              >
                All Providers
              </button>
              {sections.map((section) => (
                <button
                  key={section.provider}
                  onClick={() => setSelectedProvider(section.provider)}
                  className={`px-3 py-2 rounded-lg text-xs font-medium whitespace-nowrap transition-colors flex items-center gap-1.5 ${
                    selectedProvider === section.provider
                      ? "bg-primary text-primary-foreground"
                      : "bg-muted text-muted-foreground hover:text-foreground"
                  }`}
                >
                  <span
                    className="w-2 h-2 rounded-full"
                    style={{ backgroundColor: section.color }}
                  />
                  {section.provider.split(" ")[0]}
                </button>
              ))}
            </div>
          )}
        </div>

        {/* Adoption Filter Row */}
        <div className="flex items-center gap-2 mt-3 overflow-x-auto pb-1">
          <span className="text-xs text-muted-foreground whitespace-nowrap">Adoption:</span>
          <button
            onClick={() => setSelectedAdoption(null)}
            className={`px-2 py-1 rounded text-[10px] font-medium whitespace-nowrap transition-colors ${
              !selectedAdoption
                ? "bg-foreground text-background"
                : "bg-muted text-muted-foreground hover:text-foreground"
            }`}
          >
            All
          </button>
          {(Object.keys(adoptionConfig) as AdoptionLevel[]).map((level) => (
            <button
              key={level}
              onClick={() => setSelectedAdoption(level)}
              className={`px-2 py-1 rounded text-[10px] font-medium whitespace-nowrap transition-colors border ${
                selectedAdoption === level
                  ? `${adoptionConfig[level].bg} ${adoptionConfig[level].text} ${adoptionConfig[level].border}`
                  : "border-transparent bg-muted text-muted-foreground hover:text-foreground"
              }`}
            >
              {adoptionConfig[level].label}
            </button>
          ))}
          {hasActiveFilters && (
            <button
              onClick={clearFilters}
              className="ml-auto px-2 py-1 rounded text-[10px] font-medium text-muted-foreground hover:text-foreground flex items-center gap-1"
            >
              <svg className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
              Clear
            </button>
          )}
        </div>

        {/* Results count */}
        {hasActiveFilters && (
          <div className="mt-2 text-xs text-muted-foreground">
            Showing {filteredToolCount} of {totalTools} tools
          </div>
        )}
      </div>

      {/* Tool Sections */}
      {filteredSections.length === 0 ? (
        <div className="text-center py-12">
          <svg className="h-12 w-12 mx-auto text-muted-foreground/50 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.172 16.172a4 4 0 015.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <p className="text-muted-foreground">No tools match your filters</p>
          <button
            onClick={clearFilters}
            className="mt-2 text-sm text-primary hover:underline"
          >
            Clear all filters
          </button>
        </div>
      ) : (
        filteredSections.map((section) => (
          <section key={section.provider} className="space-y-6">
            {/* Provider Header */}
            <div className="flex items-center gap-3">
              <span
                className="w-1.5 h-8 rounded-full"
                style={{ backgroundColor: section.color }}
              />
              <div>
                <h2
                  id={slugifyHeading(section.provider)}
                  className="text-xl sm:text-2xl font-bold text-foreground"
                >
                  {section.provider}
                </h2>
                <p className="text-sm text-muted-foreground">
                  {section.groups.length} categories, {section.groups.reduce((sum, g) => sum + g.entries.length, 0)} tools
                </p>
              </div>
            </div>

            {/* Groups */}
            <div className="space-y-6">
              {section.groups.map((group) => (
                <div
                  key={`${section.provider}-${group.name}`}
                  className="rounded-xl border border-border bg-card/30 overflow-hidden"
                >
                  {/* Group Header */}
                  <div
                    className="flex items-center justify-between px-4 py-3 border-b border-border"
                    style={{ borderLeftWidth: 3, borderLeftColor: section.color }}
                  >
                    <h3
                      id={slugifyHeading(`${section.provider}-${group.name}`)}
                      className="text-sm sm:text-base font-semibold text-foreground"
                    >
                      {group.name}
                    </h3>
                    <span className="text-[10px] font-medium text-muted-foreground bg-muted px-2 py-0.5 rounded-full">
                      {group.entries.length} tools
                    </span>
                  </div>

                  {/* Tools Table */}
                  <div className="overflow-x-auto">
                    <table className="min-w-full text-sm">
                      <thead className="bg-muted/30 text-[10px] uppercase tracking-wider text-muted-foreground">
                        <tr>
                          <th className="px-4 py-2.5 text-left font-medium">Tool</th>
                          <th className="px-4 py-2.5 text-left font-medium hidden sm:table-cell">Summary</th>
                          <th className="px-4 py-2.5 text-left font-medium hidden lg:table-cell">Adoption</th>
                          <th className="px-4 py-2.5 w-8"></th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-border/50">
                        {group.entries.map((entry) => {
                          const toolId = `${section.provider}-${group.name}-${entry.tool}`;
                          return (
                            <ToolRow
                              key={toolId}
                              entry={entry}
                              isExpanded={expandedTools.has(toolId)}
                              onToggle={() => toggleTool(toolId)}
                              providerColor={section.color}
                            />
                          );
                        })}
                      </tbody>
                    </table>
                  </div>
                </div>
              ))}
            </div>
          </section>
        ))
      )}

      {/* Legend */}
      <div className="rounded-xl border border-border bg-muted/20 p-4 sm:p-6">
        <h3 className="text-sm font-semibold text-foreground mb-4">Adoption Levels Guide</h3>
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
          {(Object.entries(adoptionConfig) as [AdoptionLevel, typeof adoptionConfig[AdoptionLevel]][]).map(([level, config]) => (
            <div key={level} className="flex items-center gap-2">
              <span className={`inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-semibold uppercase tracking-wider ${config.bg} ${config.text} border ${config.border}`}>
                {config.label}
              </span>
              <span className="text-xs text-muted-foreground">
                {level === "universal" && "Ubiquitous"}
                {level === "standard" && "Default choice"}
                {level === "high" && "Strong preference"}
                {level === "common" && "Widely used"}
                {level === "selective" && "Use case specific"}
                {level === "emerging" && "Growing adoption"}
                {level === "legacy" && "Declining"}
              </span>
            </div>
          ))}
        </div>
        <div className="mt-4 pt-4 border-t border-border">
          <div className="text-xs text-muted-foreground">
            <strong>Tip:</strong> Click any tool row to expand decision context and trade-offs for Principal TPM-level discussions.
          </div>
        </div>
      </div>
    </div>
  );
}

function KnowledgeBaseContent() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const allDocs = [...allWikiDocs, ...knowledgeBaseDocs];
  const selectedSlug = searchParams.get("doc") || (allDocs[0]?.slug ?? null);
  const selectedDoc = selectedSlug ? allDocs.find((doc) => doc.slug === selectedSlug) : null;
  const isWikiPage = selectedSlug ? isWikiSlug(selectedSlug) : false;
  const wikiSections = selectedSlug ? getWikiSectionsForSlug(selectedSlug) : [];
  const contentRef = useRef<HTMLDivElement | null>(null);
  const scrollContainerRef = useRef<HTMLElement | null>(null);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [isMobile, setIsMobile] = useState(false);
  const [activeHeadingId, setActiveHeadingId] = useState("");
  const [sectionsOpen, setSectionsOpen] = useState({
    // Part I
    cloudEconomics: false,
    slaMathematics: false,
    compliance: false,
    riskQuantification: false,
    // Part II
    scalingArchitecture: false,
    networkingTraffic: false,
    database: false,
    migration: false,
    communication: false,
    // Part III
    distributedConsensus: false,
    globalArchitecture: false,
    resiliencyPatterns: false,
    probabilisticDataStructures: false,
    aiMlInfrastructure: false,
    observability: false,
    securityArchitecture: false,
    // Wiki
    wiki: false,
  });

  // Process content: strip duplicate title and extract headings
  const { processedContent, headings } = useMemo(() => {
    if (!selectedDoc) return { processedContent: "", headings: [] };
    if (isWikiPage && wikiSections.length > 0) {
      const wikiHeadings: TocItem[] = [];
      wikiSections.forEach((section) => {
        wikiHeadings.push({
          id: slugifyHeading(section.provider),
          text: section.provider,
          level: 2,
        });
        section.groups.forEach((group) => {
          wikiHeadings.push({
            id: slugifyHeading(`${section.provider}-${group.name}`),
            text: group.name,
            level: 3,
          });
        });
      });
      return { processedContent: "", headings: wikiHeadings };
    }
    const content = stripDuplicateTitle(selectedDoc.content, selectedDoc.title);
    const headings = extractHeadings(content);
    return { processedContent: content, headings };
  }, [selectedDoc, isWikiPage, wikiSections]);

  // Track active heading on scroll
  useEffect(() => {
    if (headings.length === 0) return;

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActiveHeadingId(entry.target.id);
          }
        });
      },
      { rootMargin: "-80px 0px -80% 0px", threshold: 0 }
    );

    // Observe all heading elements
    headings.forEach((heading) => {
      const element = document.getElementById(heading.id);
      if (element) observer.observe(element);
    });

    return () => observer.disconnect();
  }, [headings]);

  // Detect mobile screen size
  useEffect(() => {
    const checkMobile = () => {
      const mobile = window.innerWidth < 768;
      setIsMobile(mobile);
      // On desktop, sidebar open by default; on mobile, closed by default
      if (!mobile) {
        setSidebarOpen(true);
      }
    };

    checkMobile();
    window.addEventListener("resize", checkMobile);
    return () => window.removeEventListener("resize", checkMobile);
  }, []);

  const handleDocSelect = (slug: string) => {
    router.push(`/nebula/knowledge-base?doc=${slug}`);
    // Close sidebar on mobile after selection
    if (isMobile) {
      setSidebarOpen(false);
    }
  };

  // Get prev/next documents for bottom navigation
  const currentIndex = allDocs.findIndex((d) => d.slug === selectedSlug);
  const prevDoc = currentIndex > 0 ? allDocs[currentIndex - 1] : null;
  const nextDoc = currentIndex < allDocs.length - 1 ? allDocs[currentIndex + 1] : null;
  // Part I: Strategy & Business Physics
  const cloudEconomicsDocs = getOrderedDocs(knowledgeBaseDocs, CLOUD_ECONOMICS_ORDER);
  const slaMathematicsDocs = getOrderedDocs(knowledgeBaseDocs, SLA_MATHEMATICS_ORDER);
  const complianceDocs = getOrderedDocs(knowledgeBaseDocs, COMPLIANCE_ORDER);
  const riskQuantificationDocs = getOrderedDocs(knowledgeBaseDocs, RISK_QUANTIFICATION_ORDER);

  // Part II: Core Infrastructure
  const scalingArchitectureDocs = getOrderedDocs(knowledgeBaseDocs, SCALING_ARCHITECTURE_ORDER);
  const networkingTrafficDocs = getOrderedDocs(knowledgeBaseDocs, NETWORKING_TRAFFIC_ORDER);
  const databaseDeepDiveDocs = getOrderedDocs(knowledgeBaseDocs, DATABASE_DEEP_DIVE_ORDER);
  const migrationPatternDocs = getOrderedDocs(knowledgeBaseDocs, MIGRATION_PATTERNS_ORDER);
  const communicationPatternDocs = getOrderedDocs(knowledgeBaseDocs, COMMUNICATION_PATTERNS_ORDER);

  // Part III: Advanced & AI
  const distributedConsensusDocs = getOrderedDocs(knowledgeBaseDocs, DISTRIBUTED_CONSENSUS_ORDER);
  const globalArchitectureDocs = getOrderedDocs(knowledgeBaseDocs, GLOBAL_ARCHITECTURE_ORDER);
  const resiliencyPatternsDocs = getOrderedDocs(knowledgeBaseDocs, RESILIENCY_PATTERNS_ORDER);
  const probabilisticDataStructuresDocs = getOrderedDocs(knowledgeBaseDocs, PROBABILISTIC_DATA_STRUCTURES_ORDER);
  const aiMlInfrastructureDocs = getOrderedDocs(knowledgeBaseDocs, AI_ML_INFRASTRUCTURE_ORDER);
  const observabilityDocs = getOrderedDocs(knowledgeBaseDocs, OBSERVABILITY_ORDER);
  const securityArchitectureDocs = getOrderedDocs(knowledgeBaseDocs, SECURITY_ARCHITECTURE_ORDER);

  return (
    <div className="min-h-screen flex relative">
      {/* Mobile Overlay */}
      {isMobile && sidebarOpen && (
        <div
          className="fixed inset-0 bg-black/50 z-20 md:hidden"
          onClick={() => setSidebarOpen(false)}
        />
      )}

      {/* Sidebar */}
      <aside
        className={`${
          sidebarOpen ? "translate-x-0" : "-translate-x-full"
        } ${
          isMobile
            ? "fixed inset-y-0 left-0 z-30 w-72"
            : "relative flex-shrink-0 w-72"
        } border-r border-border bg-background transition-transform duration-300`}
      >
        <div className="w-72 h-full flex flex-col">
          {/* Sidebar Header */}
          <div className="p-4 border-b border-border bg-gradient-to-r from-primary/5 to-transparent">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
                  <svg
                    className="h-5 w-5 text-primary"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"
                    />
                  </svg>
                </div>
                <div>
                  <h1 className="text-lg font-semibold text-foreground">Knowledge Base</h1>
                  <p className="text-xs text-muted-foreground">Professor Gemini Guides</p>
                </div>
              </div>
              {/* Mobile close button */}
              {isMobile && (
                <button
                  onClick={() => setSidebarOpen(false)}
                  className="p-1.5 rounded-lg hover:bg-muted transition-colors"
                >
                  <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              )}
            </div>
            <div className="mt-3 text-xs text-muted-foreground">
              {allDocs.length} documents
            </div>
          </div>

          {/* Document List */}
          <nav className="flex-1 overflow-y-auto p-2">
            <div className="space-y-4">
              {/* Wiki Section */}
              <div className="space-y-1">
                <div className="px-2 py-1.5 bg-amber-500/10 rounded-md border border-amber-500/20">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-amber-600 dark:text-amber-400">Infrastructure Wiki</span>
                </div>
                <button
                  type="button"
                  onClick={() => setSectionsOpen((prev) => ({ ...prev, wiki: !prev.wiki }))}
                  className="w-full text-left px-3 py-2 rounded-lg transition-colors hover:bg-muted text-foreground flex items-center justify-between"
                >
                  <div>
                    <div className="font-medium text-sm">Tools & Definitions</div>
                    <div className="text-xs text-muted-foreground mt-0.5">Complete tools index</div>
                  </div>
                  <span className="text-xs">{sectionsOpen.wiki ? "▾" : "▸"}</span>
                </button>
                {sectionsOpen.wiki && (
                  <div className="ml-3 space-y-0.5">
                    <button
                      type="button"
                      onClick={() => handleDocSelect(knowledgeBaseWikiDoc.slug)}
                      className={`w-full text-left px-3 py-1.5 rounded-lg transition-colors ${
                        selectedSlug === knowledgeBaseWikiDoc.slug
                          ? "bg-primary/10 text-primary border border-primary/30"
                          : "hover:bg-muted text-foreground"
                      }`}
                    >
                      <div className="font-medium text-sm">All Providers</div>
                    </button>
                    <button
                      type="button"
                      onClick={() => handleDocSelect(wikiAwsDoc.slug)}
                      className={`w-full text-left px-3 py-1.5 rounded-lg transition-colors flex items-center gap-2 ${
                        selectedSlug === wikiAwsDoc.slug
                          ? "bg-primary/10 text-primary border border-primary/30"
                          : "hover:bg-muted text-foreground"
                      }`}
                    >
                      <span className="w-2 h-2 rounded-full bg-orange-500 flex-shrink-0" />
                      <div className="font-medium text-sm">AWS</div>
                    </button>
                    <button
                      type="button"
                      onClick={() => handleDocSelect(wikiGcpDoc.slug)}
                      className={`w-full text-left px-3 py-1.5 rounded-lg transition-colors flex items-center gap-2 ${
                        selectedSlug === wikiGcpDoc.slug
                          ? "bg-primary/10 text-primary border border-primary/30"
                          : "hover:bg-muted text-foreground"
                      }`}
                    >
                      <span className="w-2 h-2 rounded-full bg-blue-500 flex-shrink-0" />
                      <div className="font-medium text-sm">Google Cloud</div>
                    </button>
                    <button
                      type="button"
                      onClick={() => handleDocSelect(wikiAzureDoc.slug)}
                      className={`w-full text-left px-3 py-1.5 rounded-lg transition-colors flex items-center gap-2 ${
                        selectedSlug === wikiAzureDoc.slug
                          ? "bg-primary/10 text-primary border border-primary/30"
                          : "hover:bg-muted text-foreground"
                      }`}
                    >
                      <span className="w-2 h-2 rounded-full bg-cyan-500 flex-shrink-0" />
                      <div className="font-medium text-sm">Microsoft Azure</div>
                    </button>
                    <button
                      type="button"
                      onClick={() => handleDocSelect(wikiCrossCloudDoc.slug)}
                      className={`w-full text-left px-3 py-1.5 rounded-lg transition-colors flex items-center gap-2 ${
                        selectedSlug === wikiCrossCloudDoc.slug
                          ? "bg-primary/10 text-primary border border-primary/30"
                          : "hover:bg-muted text-foreground"
                      }`}
                    >
                      <span className="w-2 h-2 rounded-full bg-purple-500 flex-shrink-0" />
                      <div className="font-medium text-sm">Cross-Cloud</div>
                    </button>
                  </div>
                )}
              </div>

              {/* ═══════════════════════════════════════════════════════════════ */}
              {/* PART I: Strategy & Business Physics */}
              {/* ═══════════════════════════════════════════════════════════════ */}
              <div className="px-2 py-1.5 bg-blue-500/10 rounded-md border border-blue-500/20">
                <span className="text-[10px] font-bold uppercase tracking-wider text-blue-500">Part I: Strategy &amp; Business Physics</span>
              </div>

              {cloudEconomicsDocs.length > 0 && (
                <div>
                  <button
                    type="button"
                    onClick={() => setSectionsOpen((prev) => ({ ...prev, cloudEconomics: !prev.cloudEconomics }))}
                    className="w-full px-2 py-1 flex items-center justify-between text-[11px] font-semibold uppercase tracking-wide text-muted-foreground hover:text-foreground transition-colors"
                  >
                    <span>1.1 Cloud Economics (FinOps)</span>
                    <span className="text-xs">{sectionsOpen.cloudEconomics ? "▾" : "▸"}</span>
                  </button>
                  {sectionsOpen.cloudEconomics && (
                    <div className="space-y-1 mt-1">
                      {cloudEconomicsDocs.map((doc) => (
                        <button key={doc.slug} onClick={() => handleDocSelect(doc.slug)} className={`w-full text-left px-3 py-2.5 rounded-lg transition-colors ${selectedSlug === doc.slug ? "bg-primary/10 text-primary border border-primary/30" : "hover:bg-muted text-foreground"}`}>
                          <div className="font-medium text-sm truncate">{doc.title}</div>
                          <div className="text-xs text-muted-foreground mt-0.5">{formatDate(doc.date)}</div>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {slaMathematicsDocs.length > 0 && (
                <div>
                  <button
                    type="button"
                    onClick={() => setSectionsOpen((prev) => ({ ...prev, slaMathematics: !prev.slaMathematics }))}
                    className="w-full px-2 py-1 flex items-center justify-between text-[11px] font-semibold uppercase tracking-wide text-muted-foreground hover:text-foreground transition-colors"
                  >
                    <span>1.2 SLA Mathematics</span>
                    <span className="text-xs">{sectionsOpen.slaMathematics ? "▾" : "▸"}</span>
                  </button>
                  {sectionsOpen.slaMathematics && (
                    <div className="space-y-1 mt-1">
                      {slaMathematicsDocs.map((doc) => (
                        <button key={doc.slug} onClick={() => handleDocSelect(doc.slug)} className={`w-full text-left px-3 py-2.5 rounded-lg transition-colors ${selectedSlug === doc.slug ? "bg-primary/10 text-primary border border-primary/30" : "hover:bg-muted text-foreground"}`}>
                          <div className="font-medium text-sm truncate">{doc.title}</div>
                          <div className="text-xs text-muted-foreground mt-0.5">{formatDate(doc.date)}</div>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {complianceDocs.length > 0 && (
                <div>
                  <button
                    type="button"
                    onClick={() => setSectionsOpen((prev) => ({ ...prev, compliance: !prev.compliance }))}
                    className="w-full px-2 py-1 flex items-center justify-between text-[11px] font-semibold uppercase tracking-wide text-muted-foreground hover:text-foreground transition-colors"
                  >
                    <span>1.3 Compliance &amp; Data Sovereignty</span>
                    <span className="text-xs">{sectionsOpen.compliance ? "▾" : "▸"}</span>
                  </button>
                  {sectionsOpen.compliance && (
                    <div className="space-y-1 mt-1">
                      {complianceDocs.map((doc) => (
                        <button key={doc.slug} onClick={() => handleDocSelect(doc.slug)} className={`w-full text-left px-3 py-2.5 rounded-lg transition-colors ${selectedSlug === doc.slug ? "bg-primary/10 text-primary border border-primary/30" : "hover:bg-muted text-foreground"}`}>
                          <div className="font-medium text-sm truncate">{doc.title}</div>
                          <div className="text-xs text-muted-foreground mt-0.5">{formatDate(doc.date)}</div>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {riskQuantificationDocs.length > 0 && (
                <div>
                  <button
                    type="button"
                    onClick={() => setSectionsOpen((prev) => ({ ...prev, riskQuantification: !prev.riskQuantification }))}
                    className="w-full px-2 py-1 flex items-center justify-between text-[11px] font-semibold uppercase tracking-wide text-muted-foreground hover:text-foreground transition-colors"
                  >
                    <span>1.4 Risk Quantification</span>
                    <span className="text-xs">{sectionsOpen.riskQuantification ? "▾" : "▸"}</span>
                  </button>
                  {sectionsOpen.riskQuantification && (
                    <div className="space-y-1 mt-1">
                      {riskQuantificationDocs.map((doc) => (
                        <button key={doc.slug} onClick={() => handleDocSelect(doc.slug)} className={`w-full text-left px-3 py-2.5 rounded-lg transition-colors ${selectedSlug === doc.slug ? "bg-primary/10 text-primary border border-primary/30" : "hover:bg-muted text-foreground"}`}>
                          <div className="font-medium text-sm truncate">{doc.title}</div>
                          <div className="text-xs text-muted-foreground mt-0.5">{formatDate(doc.date)}</div>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {/* ═══════════════════════════════════════════════════════════════ */}
              {/* PART II: Core Infrastructure */}
              {/* ═══════════════════════════════════════════════════════════════ */}
              <div className="px-2 py-1.5 bg-green-500/10 rounded-md border border-green-500/20 mt-4">
                <span className="text-[10px] font-bold uppercase tracking-wider text-green-500">Part II: Core Infrastructure</span>
              </div>

              {scalingArchitectureDocs.length > 0 && (
                <div>
                  <button
                    type="button"
                    onClick={() => setSectionsOpen((prev) => ({ ...prev, scalingArchitecture: !prev.scalingArchitecture }))}
                    className="w-full px-2 py-1 flex items-center justify-between text-[11px] font-semibold uppercase tracking-wide text-muted-foreground hover:text-foreground transition-colors"
                  >
                    <span>2.1 Scaling Architecture</span>
                    <span className="text-xs">{sectionsOpen.scalingArchitecture ? "▾" : "▸"}</span>
                  </button>
                  {sectionsOpen.scalingArchitecture && (
                    <div className="space-y-1 mt-1">
                      {scalingArchitectureDocs.map((doc) => (
                        <button key={doc.slug} onClick={() => handleDocSelect(doc.slug)} className={`w-full text-left px-3 py-2.5 rounded-lg transition-colors ${selectedSlug === doc.slug ? "bg-primary/10 text-primary border border-primary/30" : "hover:bg-muted text-foreground"}`}>
                          <div className="font-medium text-sm truncate">{doc.title}</div>
                          <div className="text-xs text-muted-foreground mt-0.5">{formatDate(doc.date)}</div>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {networkingTrafficDocs.length > 0 && (
                <div>
                  <button
                    type="button"
                    onClick={() => setSectionsOpen((prev) => ({ ...prev, networkingTraffic: !prev.networkingTraffic }))}
                    className="w-full px-2 py-1 flex items-center justify-between text-[11px] font-semibold uppercase tracking-wide text-muted-foreground hover:text-foreground transition-colors"
                  >
                    <span>2.2 Networking &amp; Traffic</span>
                    <span className="text-xs">{sectionsOpen.networkingTraffic ? "▾" : "▸"}</span>
                  </button>
                  {sectionsOpen.networkingTraffic && (
                    <div className="space-y-1 mt-1">
                      {networkingTrafficDocs.map((doc) => (
                        <button key={doc.slug} onClick={() => handleDocSelect(doc.slug)} className={`w-full text-left px-3 py-2.5 rounded-lg transition-colors ${selectedSlug === doc.slug ? "bg-primary/10 text-primary border border-primary/30" : "hover:bg-muted text-foreground"}`}>
                          <div className="font-medium text-sm truncate">{doc.title}</div>
                          <div className="text-xs text-muted-foreground mt-0.5">{formatDate(doc.date)}</div>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {databaseDeepDiveDocs.length > 0 && (
                <div>
                  <button
                    type="button"
                    onClick={() => setSectionsOpen((prev) => ({ ...prev, database: !prev.database }))}
                    className="w-full px-2 py-1 flex items-center justify-between text-[11px] font-semibold uppercase tracking-wide text-muted-foreground hover:text-foreground transition-colors"
                  >
                    <span>2.3 Database Deep Dive</span>
                    <span className="text-xs">{sectionsOpen.database ? "▾" : "▸"}</span>
                  </button>
                  {sectionsOpen.database && (
                    <div className="space-y-1 mt-1">
                      {databaseDeepDiveDocs.map((doc) => (
                        <button key={doc.slug} onClick={() => handleDocSelect(doc.slug)} className={`w-full text-left px-3 py-2.5 rounded-lg transition-colors ${selectedSlug === doc.slug ? "bg-primary/10 text-primary border border-primary/30" : "hover:bg-muted text-foreground"}`}>
                          <div className="font-medium text-sm truncate">{doc.title}</div>
                          <div className="text-xs text-muted-foreground mt-0.5">{formatDate(doc.date)}</div>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {migrationPatternDocs.length > 0 && (
                <div>
                  <button
                    type="button"
                    onClick={() => setSectionsOpen((prev) => ({ ...prev, migration: !prev.migration }))}
                    className="w-full px-2 py-1 flex items-center justify-between text-[11px] font-semibold uppercase tracking-wide text-muted-foreground hover:text-foreground transition-colors"
                  >
                    <span>2.5 Migration Patterns</span>
                    <span className="text-xs">{sectionsOpen.migration ? "▾" : "▸"}</span>
                  </button>
                  {sectionsOpen.migration && (
                    <div className="space-y-1 mt-1">
                      {migrationPatternDocs.map((doc) => (
                        <button key={doc.slug} onClick={() => handleDocSelect(doc.slug)} className={`w-full text-left px-3 py-2.5 rounded-lg transition-colors ${selectedSlug === doc.slug ? "bg-primary/10 text-primary border border-primary/30" : "hover:bg-muted text-foreground"}`}>
                          <div className="font-medium text-sm truncate">{doc.title}</div>
                          <div className="text-xs text-muted-foreground mt-0.5">{formatDate(doc.date)}</div>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {communicationPatternDocs.length > 0 && (
                <div>
                  <button
                    type="button"
                    onClick={() => setSectionsOpen((prev) => ({ ...prev, communication: !prev.communication }))}
                    className="w-full px-2 py-1 flex items-center justify-between text-[11px] font-semibold uppercase tracking-wide text-muted-foreground hover:text-foreground transition-colors"
                  >
                    <span>2.6 Communication Patterns</span>
                    <span className="text-xs">{sectionsOpen.communication ? "▾" : "▸"}</span>
                  </button>
                  {sectionsOpen.communication && (
                    <div className="space-y-1 mt-1">
                      {communicationPatternDocs.map((doc) => (
                        <button key={doc.slug} onClick={() => handleDocSelect(doc.slug)} className={`w-full text-left px-3 py-2.5 rounded-lg transition-colors ${selectedSlug === doc.slug ? "bg-primary/10 text-primary border border-primary/30" : "hover:bg-muted text-foreground"}`}>
                          <div className="font-medium text-sm truncate">{doc.title}</div>
                          <div className="text-xs text-muted-foreground mt-0.5">{formatDate(doc.date)}</div>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {/* ═══════════════════════════════════════════════════════════════ */}
              {/* PART III: Advanced & AI */}
              {/* ═══════════════════════════════════════════════════════════════ */}
              <div className="px-2 py-1.5 bg-purple-500/10 rounded-md border border-purple-500/20 mt-4">
                <span className="text-[10px] font-bold uppercase tracking-wider text-purple-500">Part III: Advanced &amp; AI</span>
              </div>

              {distributedConsensusDocs.length > 0 && (
                <div>
                  <button
                    type="button"
                    onClick={() => setSectionsOpen((prev) => ({ ...prev, distributedConsensus: !prev.distributedConsensus }))}
                    className="w-full px-2 py-1 flex items-center justify-between text-[11px] font-semibold uppercase tracking-wide text-muted-foreground hover:text-foreground transition-colors"
                  >
                    <span>3.1 Distributed Consensus</span>
                    <span className="text-xs">{sectionsOpen.distributedConsensus ? "▾" : "▸"}</span>
                  </button>
                  {sectionsOpen.distributedConsensus && (
                    <div className="space-y-1 mt-1">
                      {distributedConsensusDocs.map((doc) => (
                        <button key={doc.slug} onClick={() => handleDocSelect(doc.slug)} className={`w-full text-left px-3 py-2.5 rounded-lg transition-colors ${selectedSlug === doc.slug ? "bg-primary/10 text-primary border border-primary/30" : "hover:bg-muted text-foreground"}`}>
                          <div className="font-medium text-sm truncate">{doc.title}</div>
                          <div className="text-xs text-muted-foreground mt-0.5">{formatDate(doc.date)}</div>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {globalArchitectureDocs.length > 0 && (
                <div>
                  <button
                    type="button"
                    onClick={() => setSectionsOpen((prev) => ({ ...prev, globalArchitecture: !prev.globalArchitecture }))}
                    className="w-full px-2 py-1 flex items-center justify-between text-[11px] font-semibold uppercase tracking-wide text-muted-foreground hover:text-foreground transition-colors"
                  >
                    <span>3.2 Global Architecture</span>
                    <span className="text-xs">{sectionsOpen.globalArchitecture ? "▾" : "▸"}</span>
                  </button>
                  {sectionsOpen.globalArchitecture && (
                    <div className="space-y-1 mt-1">
                      {globalArchitectureDocs.map((doc) => (
                        <button key={doc.slug} onClick={() => handleDocSelect(doc.slug)} className={`w-full text-left px-3 py-2.5 rounded-lg transition-colors ${selectedSlug === doc.slug ? "bg-primary/10 text-primary border border-primary/30" : "hover:bg-muted text-foreground"}`}>
                          <div className="font-medium text-sm truncate">{doc.title}</div>
                          <div className="text-xs text-muted-foreground mt-0.5">{formatDate(doc.date)}</div>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {resiliencyPatternsDocs.length > 0 && (
                <div>
                  <button
                    type="button"
                    onClick={() => setSectionsOpen((prev) => ({ ...prev, resiliencyPatterns: !prev.resiliencyPatterns }))}
                    className="w-full px-2 py-1 flex items-center justify-between text-[11px] font-semibold uppercase tracking-wide text-muted-foreground hover:text-foreground transition-colors"
                  >
                    <span>3.3 Resiliency Patterns</span>
                    <span className="text-xs">{sectionsOpen.resiliencyPatterns ? "▾" : "▸"}</span>
                  </button>
                  {sectionsOpen.resiliencyPatterns && (
                    <div className="space-y-1 mt-1">
                      {resiliencyPatternsDocs.map((doc) => (
                        <button key={doc.slug} onClick={() => handleDocSelect(doc.slug)} className={`w-full text-left px-3 py-2.5 rounded-lg transition-colors ${selectedSlug === doc.slug ? "bg-primary/10 text-primary border border-primary/30" : "hover:bg-muted text-foreground"}`}>
                          <div className="font-medium text-sm truncate">{doc.title}</div>
                          <div className="text-xs text-muted-foreground mt-0.5">{formatDate(doc.date)}</div>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {probabilisticDataStructuresDocs.length > 0 && (
                <div>
                  <button
                    type="button"
                    onClick={() => setSectionsOpen((prev) => ({ ...prev, probabilisticDataStructures: !prev.probabilisticDataStructures }))}
                    className="w-full px-2 py-1 flex items-center justify-between text-[11px] font-semibold uppercase tracking-wide text-muted-foreground hover:text-foreground transition-colors"
                  >
                    <span>3.4 Probabilistic Data Structures</span>
                    <span className="text-xs">{sectionsOpen.probabilisticDataStructures ? "▾" : "▸"}</span>
                  </button>
                  {sectionsOpen.probabilisticDataStructures && (
                    <div className="space-y-1 mt-1">
                      {probabilisticDataStructuresDocs.map((doc) => (
                        <button key={doc.slug} onClick={() => handleDocSelect(doc.slug)} className={`w-full text-left px-3 py-2.5 rounded-lg transition-colors ${selectedSlug === doc.slug ? "bg-primary/10 text-primary border border-primary/30" : "hover:bg-muted text-foreground"}`}>
                          <div className="font-medium text-sm truncate">{doc.title}</div>
                          <div className="text-xs text-muted-foreground mt-0.5">{formatDate(doc.date)}</div>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {aiMlInfrastructureDocs.length > 0 && (
                <div>
                  <button
                    type="button"
                    onClick={() => setSectionsOpen((prev) => ({ ...prev, aiMlInfrastructure: !prev.aiMlInfrastructure }))}
                    className="w-full px-2 py-1 flex items-center justify-between text-[11px] font-semibold uppercase tracking-wide text-muted-foreground hover:text-foreground transition-colors"
                  >
                    <span>3.5 AI/ML Infrastructure</span>
                    <span className="text-xs">{sectionsOpen.aiMlInfrastructure ? "▾" : "▸"}</span>
                  </button>
                  {sectionsOpen.aiMlInfrastructure && (
                    <div className="space-y-1 mt-1">
                      {aiMlInfrastructureDocs.map((doc) => (
                        <button key={doc.slug} onClick={() => handleDocSelect(doc.slug)} className={`w-full text-left px-3 py-2.5 rounded-lg transition-colors ${selectedSlug === doc.slug ? "bg-primary/10 text-primary border border-primary/30" : "hover:bg-muted text-foreground"}`}>
                          <div className="font-medium text-sm truncate">{doc.title}</div>
                          <div className="text-xs text-muted-foreground mt-0.5">{formatDate(doc.date)}</div>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {observabilityDocs.length > 0 && (
                <div>
                  <button
                    type="button"
                    onClick={() => setSectionsOpen((prev) => ({ ...prev, observability: !prev.observability }))}
                    className="w-full px-2 py-1 flex items-center justify-between text-[11px] font-semibold uppercase tracking-wide text-muted-foreground hover:text-foreground transition-colors"
                  >
                    <span>3.6 Observability</span>
                    <span className="text-xs">{sectionsOpen.observability ? "▾" : "▸"}</span>
                  </button>
                  {sectionsOpen.observability && (
                    <div className="space-y-1 mt-1">
                      {observabilityDocs.map((doc) => (
                        <button key={doc.slug} onClick={() => handleDocSelect(doc.slug)} className={`w-full text-left px-3 py-2.5 rounded-lg transition-colors ${selectedSlug === doc.slug ? "bg-primary/10 text-primary border border-primary/30" : "hover:bg-muted text-foreground"}`}>
                          <div className="font-medium text-sm truncate">{doc.title}</div>
                          <div className="text-xs text-muted-foreground mt-0.5">{formatDate(doc.date)}</div>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {securityArchitectureDocs.length > 0 && (
                <div>
                  <button
                    type="button"
                    onClick={() => setSectionsOpen((prev) => ({ ...prev, securityArchitecture: !prev.securityArchitecture }))}
                    className="w-full px-2 py-1 flex items-center justify-between text-[11px] font-semibold uppercase tracking-wide text-muted-foreground hover:text-foreground transition-colors"
                  >
                    <span>3.7 Security Architecture</span>
                    <span className="text-xs">{sectionsOpen.securityArchitecture ? "▾" : "▸"}</span>
                  </button>
                  {sectionsOpen.securityArchitecture && (
                    <div className="space-y-1 mt-1">
                      {securityArchitectureDocs.map((doc) => (
                        <button key={doc.slug} onClick={() => handleDocSelect(doc.slug)} className={`w-full text-left px-3 py-2.5 rounded-lg transition-colors ${selectedSlug === doc.slug ? "bg-primary/10 text-primary border border-primary/30" : "hover:bg-muted text-foreground"}`}>
                          <div className="font-medium text-sm truncate">{doc.title}</div>
                          <div className="text-xs text-muted-foreground mt-0.5">{formatDate(doc.date)}</div>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}

            </div>

            {knowledgeBaseDocs.length === 0 && (
              <div className="text-center py-8 px-4">
                <p className="text-sm text-muted-foreground">No documents yet.</p>
                <p className="text-xs text-muted-foreground mt-2">
                  Generate guides with Professor Gemini.
                </p>
              </div>
            )}
          </nav>

          {/* Back Link */}
          <div className="p-3 border-t border-border">
            <Link
              href="/nebula"
              className="flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors"
            >
              <svg
                className="h-4 w-4"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M15 19l-7-7 7-7"
                />
              </svg>
              Back to Nebula
            </Link>
          </div>
        </div>
      </aside>

      {/* Toggle Button - Desktop only */}
      {!isMobile && (
        <SidebarCollapseButton
          isCollapsed={!sidebarOpen}
          onToggle={() => setSidebarOpen(!sidebarOpen)}
          position="fixed"
          openLeftOffset="288px"
        />
      )}

      {/* Main Content */}
      <main ref={scrollContainerRef} className="flex-1 overflow-auto min-w-0">
        {selectedDoc ? (
          <div className="max-w-content mx-auto px-4 sm:px-6 py-6 sm:py-8">
            <div className={`flex ${isMobile ? "flex-col" : "gap-8"}`}>
              <div ref={contentRef} className="min-w-0 flex-1 xl:pr-72">
                {/* Mobile Header with menu button */}
                {isMobile && (
                  <div className="flex items-center gap-3 mb-4 pb-4 border-b border-border">
                    <button
                      onClick={() => setSidebarOpen(true)}
                      className="p-2 rounded-lg bg-muted hover:bg-muted/80 transition-colors"
                    >
                      <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
                      </svg>
                    </button>
                    <span className="text-sm font-medium text-muted-foreground truncate">
                      {knowledgeBaseDocs.length} docs
                    </span>
                  </div>
                )}

                {/* Document Header */}
                <header className="mb-6 sm:mb-8 pb-4 sm:pb-6 border-b border-border">
                  <h1 className="text-xl sm:text-2xl md:text-3xl font-bold text-foreground">
                    {selectedDoc.title}
                  </h1>
                  <div className="mt-2 sm:mt-3 flex flex-wrap items-center gap-2 sm:gap-4 text-sm text-muted-foreground">
                    <span>{formatDate(selectedDoc.date)}</span>
                    <span className="hidden sm:inline text-border">|</span>
                    <span className="font-mono text-xs bg-muted px-2 py-1 rounded truncate max-w-[200px] sm:max-w-none">
                      {selectedDoc.sourceFile}
                    </span>
                  </div>
                </header>

                {/* Table of Contents */}
                <TableOfContents headings={headings} activeId={activeHeadingId} />

                {/* Document Content */}
                <article className="prose prose-neutral dark:prose-invert max-w-none prose-headings:scroll-mt-20 prose-a:text-primary prose-code:before:content-none prose-code:after:content-none prose-code:bg-muted prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded prose-pre:bg-muted prose-pre:border prose-pre:border-border prose-table:text-sm prose-td:px-2 prose-td:py-1.5 prose-th:px-2 prose-th:py-1.5 prose-img:rounded-lg overflow-x-hidden">
                  {isWikiPage && wikiSections.length > 0 ? (
                    <div className="not-prose">
                      <WikiTables
                        sections={wikiSections}
                        title={selectedDoc?.title}
                        subtitle={selectedDoc?.content}
                      />
                    </div>
                  ) : (
                    <ReactMarkdown
                      remarkPlugins={[remarkGfm]}
                      components={{
                        code: CodeBlock,
                        // Add IDs to headings for TOC navigation
                        h2: ({ children }) => {
                          const text = String(children);
                          const id = slugifyHeading(text);
                          return <h2 id={id}>{children}</h2>;
                        },
                        h3: ({ children }) => {
                          const text = String(children);
                          const id = slugifyHeading(text);
                          return <h3 id={id}>{children}</h3>;
                        },
                        // Wrap tables in scrollable container for mobile
                        table: ({ children }) => (
                          <div className="overflow-x-auto -mx-4 px-4 sm:mx-0 sm:px-0">
                            <table className="min-w-full">{children}</table>
                          </div>
                        ),
                        // Make pre blocks scrollable
                        pre: ({ children }) => (
                          <pre className="overflow-x-auto">{children}</pre>
                        ),
                      }}
                    >
                      {processedContent}
                    </ReactMarkdown>
                  )}
                </article>

                {/* Bottom Navigation */}
                <nav className="mt-12 pt-6 border-t border-border">
                  <div className="flex flex-col sm:flex-row justify-between gap-4">
                    {prevDoc ? (
                      <Link
                        href={`/nebula/knowledge-base?doc=${prevDoc.slug}`}
                        className="group flex-1 p-4 rounded-lg border border-border hover:border-primary/50 hover:bg-primary/5 transition-colors"
                      >
                        <div className="text-xs text-muted-foreground mb-1 flex items-center gap-1">
                          <svg className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                          </svg>
                          Previous
                        </div>
                        <div className="font-medium text-foreground group-hover:text-primary transition-colors truncate">
                          {prevDoc.title}
                        </div>
                      </Link>
                    ) : (
                      <div className="flex-1" />
                    )}

                    {nextDoc ? (
                      <Link
                        href={`/nebula/knowledge-base?doc=${nextDoc.slug}`}
                        className="group flex-1 p-4 rounded-lg border border-border hover:border-primary/50 hover:bg-primary/5 transition-colors text-right"
                      >
                        <div className="text-xs text-muted-foreground mb-1 flex items-center justify-end gap-1">
                          Next
                          <svg className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                          </svg>
                        </div>
                        <div className="font-medium text-foreground group-hover:text-primary transition-colors truncate">
                          {nextDoc.title}
                        </div>
                      </Link>
                    ) : (
                      <div className="flex-1" />
                    )}
                  </div>

                  {/* Back to Nebula link */}
                  <div className="mt-6 text-center">
                    <Link
                      href="/nebula"
                      className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors"
                    >
                      <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
                      </svg>
                      Back to Nebula
                    </Link>
                  </div>
                </nav>
              </div>
              <PageMinimap
                targetRef={contentRef}
                scrollContainerRef={scrollContainerRef}
                levels={[2]}
                labelMode="roman-title"
                widthClass="w-56 lg:w-64"
                className="hidden xl:block xl:fixed xl:right-4 xl:top-24"
              />
            </div>
          </div>
        ) : (
          <div className="flex items-center justify-center h-full p-4">
            <div className="text-center">
              {isMobile && (
                <button
                  onClick={() => setSidebarOpen(true)}
                  className="mb-6 px-4 py-2 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors"
                >
                  Open Documents
                </button>
              )}
              <div className="text-5xl mb-4">📚</div>
              <h2 className="text-xl font-semibold text-foreground mb-2">
                No Document Selected
              </h2>
              <p className="text-muted-foreground">
                Select a document from the sidebar to view its contents.
              </p>
            </div>
          </div>
        )}
      </main>

      {/* Back to Top Button */}
      <BackToTopButton />
    </div>
  );
}

export default function KnowledgeBasePage() {
  return (
    <AuthGate
      storageKey="cyrus_nebula_auth"
      title="Knowledge Base"
      subtitle="Professor Gemini Guides"
    >
      <KnowledgeBaseContent />
    </AuthGate>
  );
}
