"use client";

/**
 * Knowledge Base - Professor Gemini Generated Guides
 *
 * Documents generated by Professor Gemini (gemini-responses folder)
 * Features a sidebar TOC for quick navigation between documents
 * Mobile responsive with collapsible sidebar
 */

import { useState, useEffect, useRef } from "react";
import Link from "next/link";
import { useSearchParams, useRouter } from "next/navigation";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { AuthGate } from "@/components/AuthGate";
import { SidebarCollapseButton } from "@/components/SidebarCollapseButton";
import { knowledgeBaseDocs, getKnowledgeBaseDoc } from "@/data/knowledge-base";
import mermaid from "mermaid";

// Initialize mermaid with dark mode support
mermaid.initialize({
  startOnLoad: false,
  theme: "neutral",
  securityLevel: "loose",
  fontFamily: "inherit",
});

function formatDate(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

// Mermaid diagram component
function MermaidDiagram({ chart }: { chart: string }) {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (containerRef.current) {
      const id = `mermaid-${Math.random().toString(36).substring(2, 9)}`;
      containerRef.current.innerHTML = "";

      mermaid
        .render(id, chart)
        .then(({ svg }) => {
          if (containerRef.current) {
            containerRef.current.innerHTML = svg;
          }
        })
        .catch((error) => {
          console.error("Mermaid render error:", error);
          if (containerRef.current) {
            containerRef.current.innerHTML = `<pre class="text-red-500">Diagram error: ${error.message}</pre>`;
          }
        });
    }
  }, [chart]);

  return (
    <div
      ref={containerRef}
      className="my-6 flex justify-center overflow-x-auto"
    />
  );
}

// Custom code block renderer
function CodeBlock({
  className,
  children,
}: {
  className?: string;
  children?: React.ReactNode;
}) {
  const match = /language-(\w+)/.exec(className || "");
  const language = match ? match[1] : "";
  const code = String(children).replace(/\n$/, "");

  if (language === "mermaid") {
    return <MermaidDiagram chart={code} />;
  }

  return (
    <code
      className={`${className || ""} font-mono text-sm`}
      style={{ fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace" }}
    >
      {children}
    </code>
  );
}

function KnowledgeBaseContent() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const selectedSlug = searchParams.get("doc") || (knowledgeBaseDocs[0]?.slug ?? null);
  const selectedDoc = selectedSlug ? getKnowledgeBaseDoc(selectedSlug) : null;
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [isMobile, setIsMobile] = useState(false);

  // Detect mobile screen size
  useEffect(() => {
    const checkMobile = () => {
      const mobile = window.innerWidth < 768;
      setIsMobile(mobile);
      // On desktop, sidebar open by default; on mobile, closed by default
      if (!mobile) {
        setSidebarOpen(true);
      }
    };

    checkMobile();
    window.addEventListener("resize", checkMobile);
    return () => window.removeEventListener("resize", checkMobile);
  }, []);

  const handleDocSelect = (slug: string) => {
    router.push(`/nebula/knowledge-base?doc=${slug}`);
    // Close sidebar on mobile after selection
    if (isMobile) {
      setSidebarOpen(false);
    }
  };

  // Get prev/next documents for bottom navigation
  const currentIndex = knowledgeBaseDocs.findIndex((d) => d.slug === selectedSlug);
  const prevDoc = currentIndex > 0 ? knowledgeBaseDocs[currentIndex - 1] : null;
  const nextDoc = currentIndex < knowledgeBaseDocs.length - 1 ? knowledgeBaseDocs[currentIndex + 1] : null;

  return (
    <div className="min-h-screen flex relative">
      {/* Mobile Overlay */}
      {isMobile && sidebarOpen && (
        <div
          className="fixed inset-0 bg-black/50 z-20 md:hidden"
          onClick={() => setSidebarOpen(false)}
        />
      )}

      {/* Sidebar */}
      <aside
        className={`${
          sidebarOpen ? "translate-x-0" : "-translate-x-full"
        } ${
          isMobile
            ? "fixed inset-y-0 left-0 z-30 w-72"
            : "relative flex-shrink-0 w-72"
        } border-r border-border bg-background transition-transform duration-300`}
      >
        <div className="w-72 h-full flex flex-col">
          {/* Sidebar Header */}
          <div className="p-4 border-b border-border bg-gradient-to-r from-primary/5 to-transparent">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
                  <svg
                    className="h-5 w-5 text-primary"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"
                    />
                  </svg>
                </div>
                <div>
                  <h1 className="text-lg font-semibold text-foreground">Knowledge Base</h1>
                  <p className="text-xs text-muted-foreground">Professor Gemini Guides</p>
                </div>
              </div>
              {/* Mobile close button */}
              {isMobile && (
                <button
                  onClick={() => setSidebarOpen(false)}
                  className="p-1.5 rounded-lg hover:bg-muted transition-colors"
                >
                  <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              )}
            </div>
            <div className="mt-3 text-xs text-muted-foreground">
              {knowledgeBaseDocs.length} documents
            </div>
          </div>

          {/* Document List */}
          <nav className="flex-1 overflow-y-auto p-2">
            <div className="space-y-1">
              {knowledgeBaseDocs.map((doc) => (
                <button
                  key={doc.slug}
                  onClick={() => handleDocSelect(doc.slug)}
                  className={`w-full text-left px-3 py-2.5 rounded-lg transition-colors ${
                    selectedSlug === doc.slug
                      ? "bg-primary/10 text-primary border border-primary/30"
                      : "hover:bg-muted text-foreground"
                  }`}
                >
                  <div className="font-medium text-sm truncate">{doc.title}</div>
                  <div className="text-xs text-muted-foreground mt-0.5">
                    {formatDate(doc.date)}
                  </div>
                </button>
              ))}
            </div>

            {knowledgeBaseDocs.length === 0 && (
              <div className="text-center py-8 px-4">
                <p className="text-sm text-muted-foreground">No documents yet.</p>
                <p className="text-xs text-muted-foreground mt-2">
                  Generate guides with Professor Gemini.
                </p>
              </div>
            )}
          </nav>

          {/* Back Link */}
          <div className="p-3 border-t border-border">
            <Link
              href="/nebula"
              className="flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors"
            >
              <svg
                className="h-4 w-4"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M15 19l-7-7 7-7"
                />
              </svg>
              Back to Nebula
            </Link>
          </div>
        </div>
      </aside>

      {/* Toggle Button - Desktop only */}
      {!isMobile && (
        <SidebarCollapseButton
          isCollapsed={!sidebarOpen}
          onToggle={() => setSidebarOpen(!sidebarOpen)}
          position="fixed"
          openLeftOffset="288px"
        />
      )}

      {/* Main Content */}
      <main className="flex-1 overflow-auto min-w-0">
        {selectedDoc ? (
          <div className="max-w-4xl mx-auto px-4 sm:px-6 py-6 sm:py-8">
            {/* Mobile Header with menu button */}
            {isMobile && (
              <div className="flex items-center gap-3 mb-4 pb-4 border-b border-border">
                <button
                  onClick={() => setSidebarOpen(true)}
                  className="p-2 rounded-lg bg-muted hover:bg-muted/80 transition-colors"
                >
                  <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
                  </svg>
                </button>
                <span className="text-sm font-medium text-muted-foreground truncate">
                  {knowledgeBaseDocs.length} docs
                </span>
              </div>
            )}

            {/* Document Header */}
            <header className="mb-6 sm:mb-8 pb-4 sm:pb-6 border-b border-border">
              <h1 className="text-xl sm:text-2xl md:text-3xl font-bold text-foreground">
                {selectedDoc.title}
              </h1>
              <div className="mt-2 sm:mt-3 flex flex-wrap items-center gap-2 sm:gap-4 text-sm text-muted-foreground">
                <span>{formatDate(selectedDoc.date)}</span>
                <span className="hidden sm:inline text-border">|</span>
                <span className="font-mono text-xs bg-muted px-2 py-1 rounded truncate max-w-[200px] sm:max-w-none">
                  {selectedDoc.sourceFile}
                </span>
              </div>
            </header>

            {/* Document Content */}
            <article className="prose prose-neutral dark:prose-invert max-w-none prose-headings:scroll-mt-20 prose-a:text-primary prose-code:before:content-none prose-code:after:content-none prose-code:bg-muted prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded prose-pre:bg-muted prose-pre:border prose-pre:border-border prose-table:text-sm prose-td:px-2 prose-td:py-1.5 prose-th:px-2 prose-th:py-1.5 prose-img:rounded-lg overflow-x-hidden">
              <ReactMarkdown
                remarkPlugins={[remarkGfm]}
                components={{
                  code: CodeBlock,
                  // Wrap tables in scrollable container for mobile
                  table: ({ children }) => (
                    <div className="overflow-x-auto -mx-4 px-4 sm:mx-0 sm:px-0">
                      <table className="min-w-full">{children}</table>
                    </div>
                  ),
                  // Make pre blocks scrollable
                  pre: ({ children }) => (
                    <pre className="overflow-x-auto">{children}</pre>
                  ),
                }}
              >
                {selectedDoc.content}
              </ReactMarkdown>
            </article>

            {/* Bottom Navigation */}
            <nav className="mt-12 pt-6 border-t border-border">
              <div className="flex flex-col sm:flex-row justify-between gap-4">
                {prevDoc ? (
                  <Link
                    href={`/nebula/knowledge-base?doc=${prevDoc.slug}`}
                    className="group flex-1 p-4 rounded-lg border border-border hover:border-primary/50 hover:bg-primary/5 transition-colors"
                  >
                    <div className="text-xs text-muted-foreground mb-1 flex items-center gap-1">
                      <svg className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                      </svg>
                      Previous
                    </div>
                    <div className="font-medium text-foreground group-hover:text-primary transition-colors truncate">
                      {prevDoc.title}
                    </div>
                  </Link>
                ) : (
                  <div className="flex-1" />
                )}

                {nextDoc ? (
                  <Link
                    href={`/nebula/knowledge-base?doc=${nextDoc.slug}`}
                    className="group flex-1 p-4 rounded-lg border border-border hover:border-primary/50 hover:bg-primary/5 transition-colors text-right"
                  >
                    <div className="text-xs text-muted-foreground mb-1 flex items-center justify-end gap-1">
                      Next
                      <svg className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                      </svg>
                    </div>
                    <div className="font-medium text-foreground group-hover:text-primary transition-colors truncate">
                      {nextDoc.title}
                    </div>
                  </Link>
                ) : (
                  <div className="flex-1" />
                )}
              </div>

              {/* Back to Nebula link */}
              <div className="mt-6 text-center">
                <Link
                  href="/nebula"
                  className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors"
                >
                  <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
                  </svg>
                  Back to Nebula
                </Link>
              </div>
            </nav>
          </div>
        ) : (
          <div className="flex items-center justify-center h-full p-4">
            <div className="text-center">
              {isMobile && (
                <button
                  onClick={() => setSidebarOpen(true)}
                  className="mb-6 px-4 py-2 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors"
                >
                  Open Documents
                </button>
              )}
              <div className="text-5xl mb-4">📚</div>
              <h2 className="text-xl font-semibold text-foreground mb-2">
                No Document Selected
              </h2>
              <p className="text-muted-foreground">
                Select a document from the sidebar to view its contents.
              </p>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}

export default function KnowledgeBasePage() {
  return (
    <AuthGate
      storageKey="cyrus_nebula_auth"
      title="Knowledge Base"
      subtitle="Professor Gemini Guides"
    >
      <KnowledgeBaseContent />
    </AuthGate>
  );
}
