"use client";

import { TeleOpsThinkingLayout } from "@/components/TeleOpsThinkingLayout";

export default function TeleOpsCorrelationRcaPage() {
  return (
    <TeleOpsThinkingLayout
      title="Correlation and RCA Logic"
      description="Deep dive into alert correlation rules and RCA generation flow"
      currentSection="correlation-rca"
    >
      <div className="mb-8 p-6 bg-card rounded-xl border border-border shadow-sm">
        <h1 className="text-2xl font-bold text-foreground mb-4">Correlation and RCA Logic</h1>
        <p className="text-muted-foreground mb-6">
          TelcoOps correlates alerts using deterministic rules to ensure transparent incident creation. RCA is then generated by a
          baseline rule set and optionally augmented with LLM reasoning.
        </p>

        <h2 className="text-lg font-semibold text-foreground mt-8 mb-3 pb-2 border-b border-border">Correlation Algorithm</h2>
        <p className="text-muted-foreground mb-3">The correlator uses three simple but effective rules:</p>
        <ol className="text-muted-foreground space-y-2 mb-4 list-decimal pl-5">
          <li><strong className="text-foreground">Tag grouping</strong>: Alerts are grouped by <code className="bg-muted px-1 rounded">tags.incident</code>.</li>
          <li><strong className="text-foreground">Threshold gating</strong>: Only groups with at least 10 alerts become incidents.</li>
          <li><strong className="text-foreground">Window constraint</strong>: Alerts must fall within a 15-minute window.</li>
        </ol>

        <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Why This Works for the MVP</h3>
        <ul className="text-muted-foreground space-y-2 mb-4 list-disc pl-5">
          <li>Gives a deterministic incident count for a demo scenario.</li>
          <li>Avoids ML-based clustering complexity.</li>
          <li>Eliminates stale incidents by correlating only the latest alert batch.</li>
        </ul>

        <h2 className="text-lg font-semibold text-foreground mt-8 mb-3 pb-2 border-b border-border">Baseline RCA</h2>
        <p className="text-muted-foreground mb-4">
          The baseline RCA uses 11 predefined pattern-matching rules. Each rule specifies keywords, a hypothesis, a confidence score
          (0.52-0.70), and supporting evidence. The algorithm searches the incident summary and first 20 alerts for pattern matches,
          selecting the rule with the highest match count. This provides a stable comparator for LLM output and ensures RCA is always
          available even if the LLM fails.
        </p>

        <h2 className="text-lg font-semibold text-foreground mt-8 mb-3 pb-2 border-b border-border">LLM RCA</h2>
        <p className="text-muted-foreground mb-4">
          LLM RCA builds a structured prompt with a fixed JSON schema, the incident payload, a sample of alerts (up to 20), and
          RAG context (top-4 results). The response must parse into JSON; otherwise the API returns a 502 error.
        </p>

        <h3 className="text-base font-semibold text-foreground mt-6 mb-2">Prompt Contract</h3>
        <ul className="text-muted-foreground space-y-2 mb-4 list-disc pl-5">
          <li>Return only JSON without code fences.</li>
          <li>Include hypotheses, confidence scores, evidence, and model metadata.</li>
          <li>Do not invent remediation commands.</li>
        </ul>

        <h2 className="text-lg font-semibold text-foreground mt-8 mb-3 pb-2 border-b border-border">RCA Output Storage</h2>
        <p className="text-muted-foreground mb-4">
          Both baseline and LLM RCA outputs are stored in the same <code className="bg-muted px-1 rounded">rca_artifacts</code> table.
          Each artifact includes duration_ms (execution timing), status (pending_review/accepted/rejected), and optional review metadata.
          LLM results additionally store the prompt and response payloads for auditability.
        </p>

        <h2 className="text-lg font-semibold text-foreground mt-8 mb-3 pb-2 border-b border-border">Design Tradeoffs</h2>
        <ul className="text-muted-foreground space-y-2 mb-4 list-disc pl-5">
          <li><strong className="text-foreground">Rule-based correlation</strong>: Clear and explainable, but not adaptive to new incident patterns.</li>
          <li><strong className="text-foreground">Baseline RCA simplicity</strong>: Limited coverage, but stabilizes trust in the system.</li>
          <li><strong className="text-foreground">LLM JSON contract</strong>: Forces structure, but still subject to occasional parse failures.</li>
        </ul>
      </div>
    </TeleOpsThinkingLayout>
  );
}
