/**
 * Knowledge Base Index (Metadata Only)
 *
 * Auto-generated by scripts/sync-nebula-docs.js
 * Source: /Users/omega/Projects/Cyrus/gemini-responses
 * Generated: 2026-02-11T15:17:01.229Z
 *
 * PERFORMANCE OPTIMIZATION:
 * - This file contains ONLY metadata (~15KB vs 3.9MB)
 * - Full content is loaded on-demand from /public/kb/{slug}.json
 * - Use the useKBContent hook to fetch content when needed
 *
 * DO NOT EDIT MANUALLY - Run "npm run sync:nebula" to regenerate
 */

export interface KnowledgeBaseDocMeta {
  slug: string;
  title: string;
  date: string;
  sourceFile: string;
}

export interface KnowledgeBaseDocFull extends KnowledgeBaseDocMeta {
  content: string;
}

export const knowledgeBaseIndex: KnowledgeBaseDocMeta[] = [
  {
    "slug": "api-platform-developer-experience-at-stripe-scale",
    "title": "API Platform & Developer Experience at Stripe Scale",
    "date": "2026-01-29",
    "sourceFile": "api-platform-stripe.md"
  },
  {
    "slug": "data-pipeline-at-netflix-batch-streaming-architecture",
    "title": "Data Pipeline at Netflix: Batch + Streaming Architecture",
    "date": "2026-01-29",
    "sourceFile": "data-pipeline-netflix.md"
  },
  {
    "slug": "data-pipeline-at-uber-batch-streaming-architecture",
    "title": "Data Pipeline at Uber: Batch + Streaming Architecture",
    "date": "2026-01-29",
    "sourceFile": "data-pipeline-uber.md"
  },
  {
    "slug": "identity-access-management-at-okta-scale",
    "title": "Identity & Access Management at Okta Scale",
    "date": "2026-01-29",
    "sourceFile": "iam-okta.md"
  },
  {
    "slug": "notification-platform-system-design",
    "title": "Notification Platform System Design",
    "date": "2026-01-29",
    "sourceFile": "notification-platform-system-design-20260129-1819.md"
  },
  {
    "slug": "payment-systems-at-visa-scale",
    "title": "Payment Systems at Visa Scale",
    "date": "2026-01-29",
    "sourceFile": "payments-at-visa.md"
  },
  {
    "slug": "resilience-disaster-recovery-at-awsamazon-scale",
    "title": "Resilience & Disaster Recovery at AWS/Amazon Scale",
    "date": "2026-01-29",
    "sourceFile": "resilience-dr-aws.md"
  },
  {
    "slug": "resilience-disaster-recovery-at-netflix-scale",
    "title": "Resilience & Disaster Recovery at Netflix Scale",
    "date": "2026-01-29",
    "sourceFile": "resilience-dr-netflix.md"
  },
  {
    "slug": "vendor-partner-program-management-at-shopify-scale",
    "title": "Vendor & Partner Program Management at Shopify Scale",
    "date": "2026-01-29",
    "sourceFile": "vendor-management-shopify.md"
  },
  {
    "slug": "agile-at-scale-program-governance",
    "title": "Agile at Scale & Program Governance",
    "date": "2026-01-23",
    "sourceFile": "agile-at-scale-program-governance-20260123-1030.md"
  },
  {
    "slug": "api-lifecycle-management-versioning",
    "title": "API Lifecycle Management & Versioning",
    "date": "2026-01-23",
    "sourceFile": "api-lifecycle-management-20260123-1102.md"
  },
  {
    "slug": "capacity-planning-demand-forecasting",
    "title": "Capacity Planning & Demand Forecasting",
    "date": "2026-01-23",
    "sourceFile": "capacity-planning-20260123-1051.md"
  },
  {
    "slug": "chaos-engineering-resilience-testing",
    "title": "Chaos Engineering & Resilience Testing",
    "date": "2026-01-23",
    "sourceFile": "chaos-engineering-resilience-20260123-1055.md"
  },
  {
    "slug": "cicd-release-engineering",
    "title": "CI/CD & Release Engineering",
    "date": "2026-01-23",
    "sourceFile": "cicd-release-engineering-20260123-1045.md"
  },
  {
    "slug": "data-governance-privacy",
    "title": "Data Governance & Privacy",
    "date": "2026-01-23",
    "sourceFile": "data-governance-privacy-20260123-1047.md"
  },
  {
    "slug": "experimentation-platforms-ab-testing",
    "title": "Experimentation Platforms & A/B Testing",
    "date": "2026-01-23",
    "sourceFile": "experimentation-platforms-20260123-1059.md"
  },
  {
    "slug": "finops-cloud-cost-engineering",
    "title": "FinOps & Cloud Cost Engineering",
    "date": "2026-01-23",
    "sourceFile": "finops-cost-engineering-20260123-1034.md"
  },
  {
    "slug": "incident-management-postmortems-for-principal-tpm-at-mag7",
    "title": "Incident Management & Postmortems for Principal TPM at Mag7",
    "date": "2026-01-23",
    "sourceFile": "incident-management-postmortems-20260123-1012.md"
  },
  {
    "slug": "multi-region-architecture-global-deployment",
    "title": "Multi-Region Architecture & Global Deployment",
    "date": "2026-01-23",
    "sourceFile": "multi-region-architecture-20260123-1057.md"
  },
  {
    "slug": "team-topologies-conways-law",
    "title": "Team Topologies & Conway's Law",
    "date": "2026-01-23",
    "sourceFile": "team-topologies-conways-law-20260123-1042.md"
  },
  {
    "slug": "technical-strategy-rfc-process",
    "title": "Technical Strategy & RFC Process",
    "date": "2026-01-23",
    "sourceFile": "technical-strategy-rfc-process-20260123-1053.md"
  },
  {
    "slug": "auto-scaling-strategies",
    "title": "Auto-scaling Strategies",
    "date": "2026-01-22",
    "sourceFile": "auto-scaling-strategies-20260122-1044.md"
  },
  {
    "slug": "availability-tiers-reality-check",
    "title": "Availability Tiers - Reality Check",
    "date": "2026-01-22",
    "sourceFile": "availability-tiers---reality-check-20260122-1032.md"
  },
  {
    "slug": "blast-radius-analysis",
    "title": "Blast Radius Analysis",
    "date": "2026-01-22",
    "sourceFile": "blast-radius-analysis-20260122-1039.md"
  },
  {
    "slug": "capex-vs-opex-mental-model",
    "title": "CAPEX vs. OPEX Mental Model",
    "date": "2026-01-22",
    "sourceFile": "capex-vs-opex-mental-model-20260122-0953.md"
  },
  {
    "slug": "cloud-economics-finops",
    "title": "Cloud Economics (FinOps)",
    "date": "2026-01-22",
    "sourceFile": "cloud-economics-finops-20260122-0729.md"
  },
  {
    "slug": "compliance-data-sovereignty",
    "title": "Compliance & Data Sovereignty",
    "date": "2026-01-22",
    "sourceFile": "compliance-data-sovereignty-20260122-0729.md"
  },
  {
    "slug": "composite-sla-calculation",
    "title": "Composite SLA Calculation",
    "date": "2026-01-22",
    "sourceFile": "composite-sla-calculation-20260122-1032.md"
  },
  {
    "slug": "cost-model-fundamentals",
    "title": "Cost Model Fundamentals",
    "date": "2026-01-22",
    "sourceFile": "cost-model-fundamentals-20260122-0939.md"
  },
  {
    "slug": "data-classification-framework",
    "title": "Data Classification Framework",
    "date": "2026-01-22",
    "sourceFile": "data-classification-framework-20260122-1035.md"
  },
  {
    "slug": "data-transfer-optimization",
    "title": "Data Transfer Optimization",
    "date": "2026-01-22",
    "sourceFile": "data-transfer-optimization-20260122-0951.md"
  },
  {
    "slug": "error-budgets-practical-application",
    "title": "Error Budgets - Practical Application",
    "date": "2026-01-22",
    "sourceFile": "error-budgets---practical-application-20260122-1033.md"
  },
  {
    "slug": "expected-loss-calculation",
    "title": "Expected Loss Calculation",
    "date": "2026-01-22",
    "sourceFile": "expected-loss-calculation-20260122-1038.md"
  },
  {
    "slug": "gdpr-what-you-must-know",
    "title": "GDPR - What You Must Know",
    "date": "2026-01-22",
    "sourceFile": "gdpr---what-you-must-know-20260122-1035.md"
  },
  {
    "slug": "horizontal-scaling-patterns",
    "title": "Horizontal Scaling Patterns",
    "date": "2026-01-22",
    "sourceFile": "horizontal-scaling-patterns-20260122-1042.md"
  },
  {
    "slug": "pci-dss-for-payment-systems",
    "title": "PCI-DSS for Payment Systems",
    "date": "2026-01-22",
    "sourceFile": "pci-dss-for-payment-systems-20260122-1036.md"
  },
  {
    "slug": "reserved-vs-spot-strategy",
    "title": "Reserved vs. Spot Strategy",
    "date": "2026-01-22",
    "sourceFile": "reserved-vs-spot-strategy-20260122-0949.md"
  },
  {
    "slug": "risk-quantification",
    "title": "Risk Quantification",
    "date": "2026-01-22",
    "sourceFile": "risk-quantification-20260122-0729.md"
  },
  {
    "slug": "scaling-architecture",
    "title": "Scaling Architecture",
    "date": "2026-01-22",
    "sourceFile": "scaling-architecture-20260122-0729.md"
  },
  {
    "slug": "sla-mathematics-reliability",
    "title": "SLA Mathematics & Reliability",
    "date": "2026-01-22",
    "sourceFile": "sla-mathematics-reliability-20260122-0729.md"
  },
  {
    "slug": "sloslasli-precision-matters",
    "title": "SLO/SLA/SLI - Precision Matters",
    "date": "2026-01-22",
    "sourceFile": "sloslasli---precision-matters-20260122-1031.md"
  },
  {
    "slug": "soc-2-trust-framework",
    "title": "SOC 2 - Trust Framework",
    "date": "2026-01-22",
    "sourceFile": "soc-2---trust-framework-20260122-1036.md"
  },
  {
    "slug": "technical-debt-quantification",
    "title": "Technical Debt Quantification",
    "date": "2026-01-22",
    "sourceFile": "technical-debt-quantification-20260122-1039.md"
  },
  {
    "slug": "vertical-scaling-limits",
    "title": "Vertical Scaling Limits",
    "date": "2026-01-22",
    "sourceFile": "vertical-scaling-limits-20260122-1041.md"
  },
  {
    "slug": "alerting-best-practices",
    "title": "Alerting Best Practices",
    "date": "2026-01-21",
    "sourceFile": "alerting-best-practices-20260121-1951.md"
  },
  {
    "slug": "api-security",
    "title": "API Security",
    "date": "2026-01-21",
    "sourceFile": "api-security-20260121-1953.md"
  },
  {
    "slug": "authentication-vs-authorization",
    "title": "Authentication vs. Authorization",
    "date": "2026-01-21",
    "sourceFile": "authentication-vs-authorization-20260121-1953.md"
  },
  {
    "slug": "bloom-filters",
    "title": "Bloom Filters",
    "date": "2026-01-21",
    "sourceFile": "bloom-filters-20260121-1947.md"
  },
  {
    "slug": "count-min-sketch",
    "title": "Count-Min Sketch",
    "date": "2026-01-21",
    "sourceFile": "count-min-sketch-20260121-1947.md"
  },
  {
    "slug": "data-architecture-patterns",
    "title": "Data Architecture Patterns",
    "date": "2026-01-21",
    "sourceFile": "data-architecture-patterns-20260121-1949.md"
  },
  {
    "slug": "distributed-tracing-architecture",
    "title": "Distributed Tracing Architecture",
    "date": "2026-01-21",
    "sourceFile": "distributed-tracing-architecture-20260121-1951.md"
  },
  {
    "slug": "encryption-strategy",
    "title": "Encryption Strategy",
    "date": "2026-01-21",
    "sourceFile": "encryption-strategy-20260121-1953.md"
  },
  {
    "slug": "hyperloglog-hll",
    "title": "HyperLogLog (HLL)",
    "date": "2026-01-21",
    "sourceFile": "hyperloglog-hll-20260121-1947.md"
  },
  {
    "slug": "llm-serving-considerations",
    "title": "LLM Serving Considerations",
    "date": "2026-01-21",
    "sourceFile": "llm-serving-considerations-20260121-1949.md"
  },
  {
    "slug": "mlops-pipeline",
    "title": "MLOps Pipeline",
    "date": "2026-01-21",
    "sourceFile": "mlops-pipeline-20260121-1949.md"
  },
  {
    "slug": "the-golden-signals-google-sre",
    "title": "The Golden Signals (Google SRE)",
    "date": "2026-01-21",
    "sourceFile": "the-golden-signals-google-sre-20260121-1951.md"
  },
  {
    "slug": "the-three-pillars-deep-dive",
    "title": "The Three Pillars - Deep Dive",
    "date": "2026-01-21",
    "sourceFile": "the-three-pillars---deep-dive-20260121-1951.md"
  },
  {
    "slug": "trade-offs-summary",
    "title": "Trade-offs Summary",
    "date": "2026-01-21",
    "sourceFile": "trade-offs-summary-20260121-1947.md"
  },
  {
    "slug": "training-vs-inference",
    "title": "Training vs. Inference",
    "date": "2026-01-21",
    "sourceFile": "training-vs-inference-20260121-1950.md"
  },
  {
    "slug": "vector-databases-and-rag",
    "title": "Vector Databases and RAG",
    "date": "2026-01-21",
    "sourceFile": "vector-databases-and-rag-20260121-1949.md"
  },
  {
    "slug": "zero-trust-architecture",
    "title": "Zero Trust Architecture",
    "date": "2026-01-21",
    "sourceFile": "zero-trust-architecture-20260121-1953.md"
  },
  {
    "slug": "asynchronous-queues-vs-pubsub",
    "title": "Asynchronous: Queues vs. Pub/Sub",
    "date": "2026-01-20",
    "sourceFile": "asynchronous-queues-vs-pubsub-20260120-1240.md"
  },
  {
    "slug": "backpressure",
    "title": "Backpressure",
    "date": "2026-01-20",
    "sourceFile": "backpressure-20260120-1301.md"
  },
  {
    "slug": "branch-by-abstraction",
    "title": "Branch by Abstraction",
    "date": "2026-01-20",
    "sourceFile": "branch-by-abstraction-20260120-0919.md"
  },
  {
    "slug": "bulkhead-pattern",
    "title": "Bulkhead Pattern",
    "date": "2026-01-20",
    "sourceFile": "bulkhead-pattern-20260120-1301.md"
  },
  {
    "slug": "change-data-capture-cdc",
    "title": "Change Data Capture (CDC)",
    "date": "2026-01-20",
    "sourceFile": "change-data-capture-cdc-20260120-0919.md"
  },
  {
    "slug": "chaos-engineering",
    "title": "Chaos Engineering",
    "date": "2026-01-20",
    "sourceFile": "chaos-engineering-20260120-1301.md"
  },
  {
    "slug": "circuit-breaker",
    "title": "Circuit Breaker",
    "date": "2026-01-20",
    "sourceFile": "circuit-breaker-20260120-1301.md"
  },
  {
    "slug": "dual-write-dual-read-pattern",
    "title": "Dual-Write / Dual-Read Pattern",
    "date": "2026-01-20",
    "sourceFile": "dual-write-dual-read-pattern-20260120-0919.md"
  },
  {
    "slug": "geo-routing",
    "title": "Geo-Routing",
    "date": "2026-01-20",
    "sourceFile": "geo-routing-20260120-1301.md"
  },
  {
    "slug": "idempotency-critical-concept",
    "title": "Idempotency - Critical Concept",
    "date": "2026-01-20",
    "sourceFile": "idempotency---critical-concept-20260120-1240.md"
  },
  {
    "slug": "latency-physics",
    "title": "Latency Physics",
    "date": "2026-01-20",
    "sourceFile": "latency-physics-20260120-1301.md"
  },
  {
    "slug": "leader-election",
    "title": "Leader Election",
    "date": "2026-01-20",
    "sourceFile": "leader-election-20260120-1255.md"
  },
  {
    "slug": "multi-region-patterns",
    "title": "Multi-Region Patterns",
    "date": "2026-01-20",
    "sourceFile": "multi-region-patterns-20260120-1302.md"
  },
  {
    "slug": "paxos-and-raft",
    "title": "Paxos and Raft",
    "date": "2026-01-20",
    "sourceFile": "paxos-and-raft-20260120-1256.md"
  },
  {
    "slug": "real-time-polling-vs-websockets",
    "title": "Real-Time: Polling vs. WebSockets",
    "date": "2026-01-20",
    "sourceFile": "real-time-polling-vs-websockets-20260120-1240.md"
  },
  {
    "slug": "retry-strategies",
    "title": "Retry Strategies",
    "date": "2026-01-20",
    "sourceFile": "retry-strategies-20260120-1301.md"
  },
  {
    "slug": "strangler-fig-pattern",
    "title": "Strangler Fig Pattern",
    "date": "2026-01-20",
    "sourceFile": "strangler-fig-pattern-20260120-0919.md"
  },
  {
    "slug": "synchronous-rest-vs-grpc-vs-graphql",
    "title": "Synchronous: REST vs. gRPC vs. GraphQL",
    "date": "2026-01-20",
    "sourceFile": "synchronous-rest-vs-grpc-vs-graphql-20260120-1240.md"
  },
  {
    "slug": "the-consensus-problem",
    "title": "The Consensus Problem",
    "date": "2026-01-20",
    "sourceFile": "the-consensus-problem-20260120-1255.md"
  },
  {
    "slug": "cap-theorem-practical-understanding",
    "title": "CAP Theorem - Practical Understanding",
    "date": "2026-01-19",
    "sourceFile": "cap-theorem---practical-understanding-20260119-0836.md"
  },
  {
    "slug": "database-sharding-strategies",
    "title": "Database Sharding Strategies",
    "date": "2026-01-19",
    "sourceFile": "database-sharding-strategies-20260119-0837.md"
  },
  {
    "slug": "replication-patterns",
    "title": "Replication Patterns",
    "date": "2026-01-19",
    "sourceFile": "replication-patterns-20260119-0837.md"
  },
  {
    "slug": "sql-vs-nosql-the-real-trade-offs",
    "title": "SQL vs. NoSQL - The Real Trade-offs",
    "date": "2026-01-19",
    "sourceFile": "sql-vs-nosql---the-real-trade-offs-20260119-0830.md"
  },
  {
    "slug": "content-delivery-networks-cdn",
    "title": "Content Delivery Networks (CDN)",
    "date": "2026-01-16",
    "sourceFile": "content-delivery-networks-cdn-20260116-1237.md"
  },
  {
    "slug": "dns-architecture",
    "title": "DNS Architecture",
    "date": "2026-01-16",
    "sourceFile": "dns-architecture-20260116-1239.md"
  },
  {
    "slug": "load-balancing-deep-dive",
    "title": "Load Balancing Deep Dive",
    "date": "2026-01-16",
    "sourceFile": "load-balancing-deep-dive-20260116-1239.md"
  },
  {
    "slug": "protocol-fundamentals",
    "title": "Protocol Fundamentals",
    "date": "2026-01-16",
    "sourceFile": "protocol-fundamentals-20260116-1239.md"
  },
  {
    "slug": "sd-tpm-lexicon",
    "title": "SD TPM Lexicon",
    "date": "January",
    "sourceFile": "sd-tpm-lexicon.md"
  }
];

export function getDocMeta(slug: string): KnowledgeBaseDocMeta | undefined {
  return knowledgeBaseIndex.find(doc => doc.slug === slug);
}

export function getAllKnowledgeBaseSlugs(): string[] {
  return knowledgeBaseIndex.map(doc => doc.slug);
}
